### ISSUE TITLE
lean-mode: make customize option to save buffers before compile

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#104]
Feature suggested by @fpvandoorn

**Comment by soonhokong** [comment]
@fpvandoorn, I found an emacs customization-variable `compilation-ask-about-save` which does the job. When its value is `t` (default), it will ask which buffers to save before compiling. When set with `nil`, it will save all modified buffers without asking.

``` elisp
(setq compilation-ask-about-save nil)
```

Since the effects are all-or-nothing, I think it's difficult to put it as a lean-mode option.

**Comment by fpvandoorn** [comment]
Ok, then I'll just add that to my .emacs file. Thanks for your effort.
