### ISSUE TITLE
Wrong displayed type in proof with multiple sorry's

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#112]
In a prove where sorry occurs multiple times, hovering over a sorry displays wrong type in minibuffer. For example, in the file

```
import data.nat
using nat
theorem foo (n : ℕ) : n = n :=
induction_on n sorry sorry
```

hovering over the **first** sorry gives `sorry : ∀ (m : nat.nat), eq m m → eq (nat.succ m) (nat.succ m)` in the minibuffer.
hovering over the second sorry gives no type in the minibuffer.

**Comment by leodemoura** [comment]
I managed to reproduce the bug.
It is a bug in Lean.
