### ISSUE TITLE
lean-mode: auto-complete doesn't recognize namespaces

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#121]
When typing

```
import data.nat
using nat

check add_zero_lef
```

and then pressing TAB to auto-complete it doesn't work (completing "nat.add_zero_lef" does work)

**Comment by soonhokong** [comment]
For now, auto-completion doesn't work for that case. @leodemoura and I are working on a better version of it. Stay tuned :-)

**Comment by soonhokong** [comment]
need to pick up `FINDP` command (bbdb13172ebf2fe2bed2f1f89cae03962692736e)

**Comment by soonhokong** [comment]
Closed by cc89cd051a9c685f12b135164972b3731c4568e8.
