### ISSUE TITLE
wrong coloring using parameter + parentheses

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#122]
When writing the argument of "parameter" in normal parentheses, the coloring of the variable name is wrong

```
section
parameter (T : Type) -- "(" gets also colored
parameter ( R : Type ) -- in addition, "R" doesn't get colored
end
```

(please tell me if such things are too small to open an issue for)

**Comment by soonhokong** [comment]
This is a bug. I'm working on it.
