### ISSUE TITLE
up arrow moves up two lines?

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#128]
When I press the up arrow key (or C-p) when my cursor is on an empty line, my cursor moves up two lines. This only happens in .lean-files, so I assume it has something to do with the lean-mode. Is this intended behavior?

**Comment by soonhokong** [comment]
I believe that this is a side-effect of using `fci-mode` (fill-column-indicator mode, that we use to display a vertical line.)
- Are you using `fci-mode`? If that is not the case, but you are experiencing the problem. Please let me know.
- If so, please remove a line containing `lean-show-rule-column-method` in your `.emacs` setup, restart emacs, and test whether you still have the problem.

**Comment by soonhokong** [comment]
This is a known issue of `fci-mode`. Please read https://github.com/alpaker/Fill-Column-Indicator/issues/31.

> But the only fix I can offer is to upgrade to Emacs rev. 112274 or later or to apply the below patch to 24.3 and rebuild. Sorry.

**Comment by fpvandoorn** [comment]
That was exactly it. Stop using fci-mode solved the problem. Thanks!
