### ISSUE TITLE
linja for cygwin

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#129]
The cygwin daily build fails because we don't have linja for cygwin.
We get the following error message

Error: we do not have ninja executable for this platform: CYGWIN_NT-6.3-1.7.31-0.272-5-3-x86_64-64bit

**Comment by soonhokong** [comment]
I see. I'll fix the problem. Also, we need to add ninja executable for 32-bit linux as @avigad reported.

**Comment by soonhokong** [comment]
04fa9e04b64799444e30a1f72016cf9d380e395a added ninja binary for 32-bit linux.

**Comment by soonhokong** [comment]
@leodemoura, do you still have a problem on cygwin? Let me take a look at the error message tomorrow morning.

**Comment by leodemoura** [comment]
I tried in the office, and it didn't work. I didn't try hard since I was in the middle of a big refactoring.
I will try again tomorrow.

**Comment by soonhokong** [comment]
For the record: the problem is that the ninja binaries that we have for CYGWIN (64bit/32bit) are not portable between two different CYGWIN installations. We decided to put a lower priority for this one.
