### ISSUE TITLE
export and TAGS

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#131]
@soonhokong 

We have a `export` command that creates abbreviations.
For example,

```
      import nat
      namespace boo
         export nat
      end boo
```

Now, `boo.add_assoc` is an abbreviation for `nat.add_assoc`. However, TAGS and `.ilean` files do not contain a declaration for `boo.add_assoc`. I think it does not make sense to jump to the `export nat` line. We should jump to `nat.add_assoc`. So, I think we should have a new "abbreviation" entry on `.ilean` files. It would be of the form

```
     a|abbreviation-name|declaration-name
```

Then, `ltags` would use this entry to "copy" the position information from `declaration-name` to `abbreviation-name`. It is not convenient to do it in lean because when we compile `export nat` we don't have `nat.ilean` in memory (only `nat.olean`).

What do you think?

**Comment by leodemoura** [comment]
The commit https://github.com/leanprover/lean/commit/c532dcfaac442f443bcef16253022064429c810b added

```
  a|abbreviation-name|declaration-name
```

to `.ilean` files.

**Comment by soonhokong** [comment]
@leodemoura, I see. I'll add the feature to `ltags`.
