### ISSUE TITLE
limit the number of errors to flycheck

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#134]
If there are two many errors, emacs becomes unusable because flycheck spends all the time processing the error messages.

**Comment by soonhokong** [comment]
@leodemoura, we can customize the variable `lean-flycheck-max-messages-to-display` (default-value = `100`) to set the limit. When the number of errors exceeds the limit `N`, we only show the first `N` messages in addition to an extra error message:

```
For performance, we only display N errors/warnings out of M.
```

where `M` is the actual number of messages we have (`M > N`)

**Comment by leodemoura** [comment]
Great!
