### ISSUE TITLE
auto-completion freezing

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#136]
It is not clear what triggers the behavior. It doesn't always happen. However, after it starts, every time auto-completion is activated it freezes emacs (I have to press Ctrl-g).

**Comment by leodemoura** [comment]
bad news, it is still freezing. I had the problem again while writing a small test.

**Comment by soonhokong** [comment]
Yep.. I'm still working on it...

**Comment by leodemoura** [comment]
I found a sequence of actions that deterministically freezes emacs (at least on my notebook).
1) open an empty `tst.lean` file
2) type `VISIT ../../`
3) wait a little bit (0.5secs) and the system is frozen.

I visited `*lean-server*` buffer, and it contained millions of copies of 

```
    The following pre-message will be thrown away:
    Sent Message:
    INFO 1
    Received Message:
    -- BEGININFO STALE NAY
    -- ENDINFO
```

**Comment by leodemoura** [comment]
I think the problem is generated because lean throws an exception and don't manage to reach the end of the file. So, the `NAY` remains there forever, and emacs keeps asking again and again.

**Comment by soonhokong** [comment]
I can also reproduce the symptom on my machine. However, this is different from the symptom that you had this afternoon.

**Comment by soonhokong** [comment]
For this one, we can have a counter on emacs side to limit the number of retries..

**Comment by leodemoura** [comment]
The counter might solve the other problem too.

I'm wondering what happens in the following scenario
1) lean-mode sends VISIT ..., and lean-server starts a thread to process it.
2) lean-mode sends an INFO L and puts a continuation C in the queue.
3) lean-server prints INFO result with NAY because worker thread did not process line L yet. (remark: C is still in the queue).
4) user modifies the buffer, and a REPLACE is sent to lean-server. When lean-server receives the REPLACE cmd, it kills the worker thread before it had the chance to reach line L.
5) C is executed, since the output contains a NAY, it asks again, and C goes back to the queue.
6) In the meantime, another query is sent to lean-server because the user is hovering over text. Now, we have two continuations.
7) Then, again the buffer is modified, and INFO result contains NAY. Now both continuations will be inserted, and the process continues, and we keep putting more and more continuation in the queue, and lean-server never has the change to process line L.

I think a continuation C should reenter the queue (because of a NAY) only when it is the only continuation in the queue. 
What do you think?

**Comment by soonhokong** [comment]
@leodemoura, thanks a lot for the comment. I think that explains the behavior. When we have NAY INFO, we re-send "INFO" command only if the following condition is satisfied:
- The current continuation is the last one in the queue
- Retry counter is less than 10 (customizable option)

The change is at bd17d07ebc6b6e2168c8406fa015efe91995a016. Could you test the latest one and let me know if you still find a problem?

**Comment by leodemoura** [comment]
I tried it this morning, and it seems to be working really well :+1:

**Comment by soonhokong** [comment]
Thank you for testing it. Let me close this one for now. If you experience a problem, please re-open this one.
