### ISSUE TITLE
flycheck leftovers

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#140]
Suppose we open a `foo.lean` file and starts editing it. Flycheck creates `flycheck_foo.lean`. 
When we close the file, flycheck deletes `flycheck_foo.lean`, but it leaves `flycheck_foo.ilean`, `flycheck_foo.olean`, `flycheck_foo.clean`, ...

**Comment by leodemoura** [comment]
The `.clean` (cache file) is being deleted every time flycheck is executed. This is really bad.
We should not delete the `.clean` files after we execute `flycheck`. Otherwise, we have to start from scratch every time.

We should review that. Possible solutions: 
1- we delete them when we close the file.
2- we delete them when we close emacs
3- we tell flycheck to use the "real" .clean file. That is, when compiling `flycheck_foo.lean`, we use `foo.clean`.

**Comment by soonhokong** [comment]
I think solution 3 is the best. It means we never create `flycheck_foo.clean`, right?

**Comment by leodemoura** [comment]
Yes, this is right.
