### ISSUE TITLE
implicit arguments in inductive definition

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#141]
I just tried to define in data.category:

```
inductive is_section {A B : ob} (f : mor A B) : Type :=
mk : ∀g, g ∘ f = id → is_section f
```

However, this raises an error (term `f` has type `mor A B` but is expected to have type `ob`), while giving explicit arguments to "is_section" is accepted:

```
inductive is_section {A B : ob} (f : mor A B) : Type :=
mk : ∀g, g ∘ f = id → is_section A B f
```

Is this a bug? If not, how is it different than the following?

```
inductive is_reflexive {T : Type} (R : T → T → Type) : Prop :=
mk : reflexive R → is_reflexive R
```

**Comment by fpvandoorn** [comment]
Note: it has something to do with defining it in a section (perhaps with parameters?) When still in the section, I have to provide the {A B : ob} explicitly, but after ending the section, they become implicit.

**Comment by fpvandoorn** [comment]
I now get a different error.

```
section
parameter {A : Type}
definition foo : A → A → Type := (λ x y, Type)
inductive bar {a b : A} (f : foo a b) :=
bar2 : bar f
end
```

error: function expected at `foo A a`

**Comment by leodemoura** [comment]
This is a different bug, it has been fixed at https://github.com/leanprover/lean/commit/5549295c4794218d8c7377ed4f36c731f29f7e63
