### ISSUE TITLE
lean-mode: emacs hangs

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#148]
Lately with Lean, emacs sometimes hangs and becomes unresponsive (until I kill the process). It has happened 3 times last 10 minutes, and once yesterday evening. I think it has to do with Lean (I didn't change anything to emacs lately). Is there a way to create/find a log file or crash report?

**Comment by leodemoura** [comment]
I have also experienced this problem the last few days. The only workaround was to restart emacs.
@soonhokong  has been working on this issue. See https://github.com/leanprover/lean/issues/136
He submitted a fix late last night. I didn't experience this problem since he submitted it.

**Comment by soonhokong** [comment]
@fpvandoorn, could you test the latest version? If you still have the same problem, please let me know.

**Comment by leodemoura** [comment]
@soonhokong Emacs is still hanging. It happened when I was adding a theorem in the end of the buffer. As before, after the behavior starts happening, it doesn't stop.
BTW, I also got the massage
`eldoc error: (wrong-type-argument characterp nil)`

**Comment by soonhokong** [comment]
@leodemoura, could you checkout the latest version and restart your emacs? I believe that 6b5e67e063b789d430a44f7cd1441afb443fc18b fixed the problem.

**Comment by leodemoura** [comment]
I have this commit. However, I'm not sure if had restarted emacs after I got. 
I did it now. I will tell if you it happens again.

**Comment by leodemoura** [comment]
It is still hanging. No clear reason. 
The _lean-server_ buffer does not contain any suspicious message.

**Comment by soonhokong** [comment]
I see. Does it only happen at the end of buffer?

**Comment by leodemoura** [comment]
No. It happened in the middle of the buffer this time.

**Comment by soonhokong** [comment]
I see. I'll take care of it.

**Comment by soonhokong** [comment]
We will add the following things to prevent emacs from hanging
- Pressing <kbd>C-g</kbd> (`keyboard-quit`) will do hard-kill (restarting lean-server, do the synchronization, etc). #158 
- Add time-limit to `WAIT` command, first ask lean-server to terminate within this limit. If lean-server keeps running, lean-mode will kill the server process and restart. #157, #156
- If you start/re-start lean-mode on a buffer with unsaved contents, lean-mode will do the synchronization #159
