### ISSUE TITLE
suppressing implicit arguments in auto-completion

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#149]
@soonhokong and @avigad, the type of most declarations contain a lot of implict arguments.
So, the type of most declarations is truncated for most elements in the auto-completion list.
To cope with this issue, I'm instantiating the implict arguments with metavariables. In this way, the type gets much smaller. I don't think this is a big problem since the user will not have to provide these arguments anyway. Here is an example

![image](https://cloud.githubusercontent.com/assets/2778936/4176409/3a28870c-3602-11e4-8d84-e99071e0c764.png)

**Comment by soonhokong** [comment]
I think the motivation is reasonable. Can we use something other than "?M_n" notation?

Let me take an example of `iff.trans` (second one in the above entries), which has the following definition:

``` lean
theorem trans {a b c : Prop} (H₁ : a ↔ b) (H₂ : b ↔ c) : a ↔ c :=
```

In the attached screenshot, we have:

``` lean
iff ?M_1 ?M_2 → iff ?M_2 ?M_3 → iff ?M_1 ?M_3
```

What about the following candidates:
1. Use `?_n`
   
   ``` lean
   iff ?₁ ?₂ → iff ?₂ ?₃ → iff ?₁ ?₃
   ```
2. Use `#n`
   
   ``` lean
   iff #1 #2 → iff #2 #3 → iff #1 #3
   ```
3. Ideally, it would be best if we can show the parameter names that users used to define the definition/theorem. For this example, we (somehow) pick up `a`, `b`, `c` from the definition and show the following:
   
   ```
   iff a b → iff b c → iff a c
   ```

What do you think?

**Comment by leodemoura** [comment]
All of them can be implemented. 
I like 3 the best, but it hides the fact that {a, b, c} are meta-variables. 
What about
        `iff ?a ?b → iff ?b ?c → iff ?a ?c`
We can also use
        `iff ?₁ ?₂ → iff ?₂ ?₃ → iff ?₁ ?₃`

**Comment by soonhokong** [comment]
I prefer `iff ?a ?b → iff ?b ?c → iff ?a ?c`. I can change `lean-mode` to replace `?a` with `a` (but use difference color!).

**Comment by leodemoura** [comment]
Cool!
I've submitted the change.
