### ISSUE TITLE
move soonhokong/lean-windows and soonhokong/lean-osx to leanprover

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#152]
BTW, they should be forks instead of full repositories.

**Comment by soonhokong** [comment]
Github doesn't allow us to fork a repository into another repository within an organization. Then, we have the following options:
- Put `lean-osx` and `lean-windows` as full repositories in `leanprover` organization (not as forks).
- Create different organizations, put them there. We even need two organization to have both of them as forks of lean.

We decided to keep them as they are for now. Let's revisit this one later.
