### ISSUE TITLE
flycheck error when opening new .lean file

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#163]
![image](https://cloud.githubusercontent.com/assets/2778936/4206226/bcea10be-3848-11e4-8a98-8c470dad86e3.png)

**Comment by leodemoura** [comment]
Update: flycheck support is completely broken in the latest version

**Comment by soonhokong** [comment]
@leodemoura, could you test?

**Comment by leodemoura** [comment]
It is working again. :+1: 

Thanks,
Leo
