### ISSUE TITLE
remove platform specific dependencies on cmake

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#166]

**Comment by soonhokong** [comment]
- We do not have platform specific dependencies on our `CMakeLists.txt` files. 
- However there are still some platform specific dependencies at files in [src/cmake/Modules](https://github.com/leanprover/lean/tree/master/src/cmake/Modules).

Let's revisit this issue when we handle #167.

**Comment by leodemoura** [comment]
> We do not have platform specific dependencies on our CMakeLists.txt files.

For building, this is true.
However, the `ctest` part depends on a bunch of bash scripts and tools such as `diff` and `grep`.
I created a bunch of `test_single.sh` and `test.sh`.

**Comment by soonhokong** [comment]
> However, the ctest part depends on a bunch of bash scripts and tools such as diff and grep.

True... :cry:
