### ISSUE TITLE
compile Lean with Visual Studio 2014

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#167]

**Comment by leodemoura** [comment]
This link might be useful in the future
http://cmaketools.codeplex.com/

**Comment by soonhokong** [comment]
cmake authors added a support for visual studio 14: http://www.cmake.org/gitweb?p=cmake.git;a=commit;h=65624c39e3f435a601760bfcb01d9cafbbfb56c1

I will check the nightly builds later: http://www.cmake.org/files/dev/?C=M;O=D

**Comment by leodemoura** [comment]
Awesome!

**Comment by leodemoura** [comment]
BTW, when I compile with Boost, lean crashes during process finalization. It actually process the .lean file correctly. I think the crash is during thread local storage finalization

**Comment by soonhokong** [comment]
Yes, I had the same behavior. It was the same when I ran a binary compiled without Boost.

**Comment by leodemoura** [comment]
We will wait the official release of VS 2014
