### ISSUE TITLE
test Lean mode on Emacs for windows

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#168]

**Comment by leodemoura** [comment]
We should make sure everything works even if msys2 python is being used.
flycheck does not work even if we consistently use msys2 python.
Users will complain about that. We fix the `/` vs `\` in different places (including lean).

**Comment by soonhokong** [comment]
In msys2, we can install two python binaries
- python2
- mingw-w64-x86_64-python2

Now, lean is working with `mingw-w64-x86_64-python2` but not with `python2`. I've updated [doc/msys2.md](https://github.com/leanprover/lean/blob/master/doc/make/msys2.md) accordingly.

If you already have installed `python2` (which is the case if you followed previous instructions), you can remove `python2` and install `mingw-w64-x86_64-python2` by running the following commands on msys2 shell:

``` bash
pacman -R python2
pacman -S mingw-w64-x86_64-python2
```

Another thing that I found during the debugging is that ninja developers decided to support only `\` on windows platform: https://groups.google.com/forum/#!topic/ninja-build/KrxvzcSJQbY

**Comment by leodemoura** [comment]
I tried that on my notebook, and it is still not working.
When I type `which python`, I get

```
/mingw64/bin/python
```

BTW, I also had to include

```
(set-language-environment "UTF-8")
```

I hope this issue will disappear after we stop generating the lean "tmp" files, and start using the `SYNC` command.

**Comment by soonhokong** [comment]
@leodemoura, could you test the latest commit? I think f8164b6a7e4c2cac663b6d20907a9520a0b596f5 and b2c8e7d364d653ce8753571c291641032213bff1 fixed the problem.

> I hope this issue will disappear after we stop generating the lean "tmp" files, and start using the SYNC command.

It should be gone too.
