### ISSUE TITLE
two strange errors

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#183]
I encountered two errors in category.lean:

The first error occurred when I rebased my category.lean on the newest master-branch. On the version I pulled this morning it worked fine. When I commit lines 115-117 in https://github.com/fpvandoorn/lean/blob/master/library/data/category.lean#L115
I get the error

```
type mismatch at definition 'inverse_unique', has type
  ∀ (ob : Type) (Cat : category ob) (A B : ob) (f : mor A B) (H H' : is_iso f),
    eq ([annotation inverse] f) ([annotation inverse] f)
but is expected to have type
  ∀ {ob : Type} {Cat : category ob} {A B : ob} {f : mor A B} (H H' : is_iso f),
    eq ([annotation inverse] f) ([annotation inverse] f)
```

Note that the type and expected type are the same modulo implicitness of arguments.

The second error happens on lines 199-207. Note that `check f ∘op g = g ∘ f` is accepted without error, but `theorem compose_op : f ∘op g = g ∘ f := rfl` gives the error that it doesn't understand the type of the theorem (the same error occurs when `rfl` is replaced by `sorry`)

**Comment by leodemoura** [comment]
The problem is the declaration

```
  theorem id_compose (ID A) ∘ id = id :=
  id_left
```

In the section, `id_compose` means `id_compose A`, where `A` is the section parameter.
I didn't implement yet the feature I suggested in the morning. 

The problem disappears after we replace it with

```
  theorem id_compose {A : Type} : (ID A) ∘ id = id :=
  id_left
```

This problem was being masked by bug #182.

**Comment by leodemoura** [comment]
In the future, `id_compose` will mean `id_compose _` since the section parameter `A` is marked implicit.
So, the change above will not be needed

**Comment by fpvandoorn** [comment]
Ah, I see the problem, and why it was masked by #181. So did the file for which I submitted a pull request not compile? It compiled for me, but maybe that was just because the "accidentally right" version of `id_compose` was still cached (I might have forgotten to run `make clean-olean` when compiling).

However, the errors in this issue are different and not solved by changing `id_compose`. I commented out the problematic parts in my pull request.

**Comment by leodemoura** [comment]
I'm investigating the `inverse_unique` problem. The second one is due opaque definitions.
If we mark `compose` and `opposite` as transparent (aka abbreviations), then the type of `theorem compose_op` type checks. Lean enforces that the type of every theorem and definition must type check outside of the module it was defined. 

Here is the change: https://github.com/leanprover/lean/commit/a305012ce5e4c085d94bd58d11b9384681e7e127
