### ISSUE TITLE
coercions too restrictive?

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#185]
The function `morphism` takes a functor, and gives the corresponding map on morphisms in the category. Its type is

```
morphism :
  Π {obC : Type} {obD : Type} {C : category obC} {D : category obD} (F : functor C D) {A B : obC},
    mor A B → mor (F A) (F B)
```

I want this to be a coercion, so that I can write `F f` for a functor `F` and morphism `f`. When I try to declare that `morphism` should be a coercion, I get the error

```
invalid coercion, type of 'functor.morphism' does not match any of the allowed expected types for coercions
(...)
```

**Comment by leodemoura** [comment]
When the coercion is to a function class, Lean tries to guess the source class. The heuristic does not work on this example. I will improve it. In the meantime, we can explicitly specify the source class.

```
coercion morphism : functor
```

Now, lean knows that morphism is a coercion from the functor-class to the function (builtin) class
