### ISSUE TITLE
only last coercion is used with multiple options

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#187]
In [category.lean](https://github.com/fpvandoorn/lean/blob/fad630f733170e1828be139c03344905be0313b1/library/struc/category.lean) I define two coercions. The object map which sends elements of `functor C D` to `obC -> obD` and the morphism map which sends `F : functor C D` to `mor A B -> mor (F A) (F B)`
However, if I then write
`(λx : obC, G (F x))`
only the second coercion is considered, since I declared that one last, and I get the error

```
term
  λ (x : obC), G
has type
  Π (x : obC), mor F ?M_2 → mor (G F) (G ?M_2)
but is expected to have type
  obC → obE
```

**Comment by leodemoura** [comment]
Let's discuss this one. @avigad and @soonhokong: it would be great to have your feedback.
In the current implementation, we can have at most one coercion between classes C and D must be active in a specific point.
Like Coq, there are three kinds of classes user-class, sort-class and function-class.
The user class is composed of inductive datatypes and opaque definitions.
Floris suggestion sounds reasonable, but we have to support multiple coercions between classes C and D.
He basically wants two different coercions from user-class functor to function-class.
By the same token, we can have multiple coercions between any pair of classes. For example, we can have the two following reasonable coercions between vector and matrix

```
     to_col  {A : Type} {n : nat} : vec A n -> matrix A n 1
     to_row {A : Type} {n : nat} : vec A n -> matrix A 1 n
```

BTW, note that the coercions are organized into namespaces. So, in the current implementation, we can have multiple coercions between C and D, and control which one is active by using the `open` command.

**Comment by avigad** [comment]
Hmm. It seems like a useful feature. It is straightforward to implement, isn't it?

I can think of other examples. For example, groups can act on different structures, so the user may want to "apply" an element g : G to elements of different structures and have the action inferred.

The main concern is whether the ambiguity will cause problems. In Floris' example, the desired coercion is unambiguous: presumably only one will type check, depending on whether the argument is in mor A B or ob C. Your example is unambiguous, unless n is 1. But if the user installs two coercions from nat to int, there is bound to be trouble!

My sense is that as long as the user can easily see the coercions, it will be o.k.

**Comment by leodemoura** [comment]
> Hmm. It seems like a useful feature. It is straightforward to implement, isn't it?

The coercion module maintains the transitive closure of a graph where the nodes are the classes and the edges are the user declared coercions.
To implement the feature above, we would have to change the representation from a graph to a multi-graph, and compute the transitive closure of this multi-graph. I would also have to add support for detecting equivalent edges. Right now, we don't need it since we just replace the edge, but if we have multiple edges we should remove duplicates.

The elaborator would also have to change. Right now, it only case-splits on coercions when the from/to classes are not known at preprocessing time.
