### ISSUE TITLE
import auto complete bug

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#189]
I got the following error message when I pressed 'TAB' after

```
import logi
```

![image](https://cloud.githubusercontent.com/assets/2778936/4266122/86b45ae8-3c73-11e4-9a0e-61d63d6c609d.png)

The auto complete only seems to work for files at `./library`

**Comment by leodemoura** [comment]
I got the error when I created a new file at `tests/lean/run/import_test.lean`

**Comment by soonhokong** [comment]
I see. I will fix it.
