### ISSUE TITLE
auto-completion types are hard to read in some color schemes

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#190]
I can barely see the type of `setoid.mk` at

![image](https://cloud.githubusercontent.com/assets/2778936/4266170/f387a20e-3c75-11e4-87b2-654b93c6ed5f.png)

Possible fixes 
- Use `?` 
- Use a different font-face

**Comment by soonhokong** [comment]
@leodemoura, please customize `lean-company-type-foreground` variable. You can do it by <kbd>C-u M-x customize-mode RET lean-mode</kbd>.
