### ISSUE TITLE
lean-mode: send VISIT buffer immediately after open

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#198]
this can reduce the creation of temporary buffers

**Comment by leodemoura** [comment]
@soonhokong here is a related question: I'm considering clearing the `lean --server` cache and reprocess the file whenever lean-mode sends a `VISIT` command. The motivation is to handle the following scenario:

1) User opens file A (that uses B)
2) User opens file B, and changes B
3) User goes back to A 
4) lean-mode sends INFO command
At this point, `lean --server` will be producing information that does not reflect the changes made in B.

**Comment by soonhokong** [comment]
Closed by e255b02fca27dcfbfb971528bb9c28f308bc07f8
