### ISSUE TITLE
implicit arguments in coercion confuses unifier

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#200]
In category.lean I define `morphism` as a coercion:

```
morphism :
  Π {obC : Type} {obD : Type} {C : category obC} {D : category obD} (F : functor C D) {A B : obC},
    mor A B → mor (F A) (F B)
```

The  following example confuses the unifier (it times out):

```
  parameters {obC obD : Type} {C : category obC} {D : category obD} (F : functor C D)
  check λ (a b : obC) (f : mor a b), F f
```

If I write the implicit arguments of `mor` explicitly, then it gives the error that `f` should have type `obC` (so it chooses the wrong coercion)

```
check λ (a b : obC) (f : @mor obC C a b), F f
```

The following does work (probably because now everything is the right alias)

```
  parameters {obC obD : Type} {C : category obC} {D : category obD} (F : functor C D)
  parameters (a b : obC) (f : including C, mor a b)
  check F f
```

full file: https://github.com/fpvandoorn/lean/blob/master/library/struc/category.lean

**Comment by leodemoura** [comment]
I'm still analyzing this file, but I've already found one problem

```
abbreviation opposite [instance] (C : category ob) : category ob :=
```

Recall that the class-instance mechanism is essentially a "Prolog" program.
The "program" above is the Horn clause

```
         category ob :- category ob
```

It can be applied indefinitely.

**Comment by fpvandoorn** [comment]
Ah, yeah, I see. It was indeed not smart to make that an instance. Removing that indeed solves the time-outs.

**Comment by leodemoura** [comment]
I found another problem. It is actually due to how `check` works in sections.
The command 

```
check λ (a b : obC) (f : @mor obC C a b), F f
```

is actually syntax sugar for

```
check λ {obC obD : Type} {C : category obC} {D : category obD} 
            (F : functor C D) (a b : obC) (f : @mor obC C a b), F f
```

since it is inside of a section.
Now, since the first arguments are implicit, the system adds metavariables

```
check (λ {obC obD : Type} {C : category obC} {D : category obD} 
              (F : functor C D) (a b : obC) (f : @mor obC C a b), F f) 
         ?M1 ?M2 ?M3 ?M4
```

Now, it has to synthesize two categories: `?M3 : category ?M1` and `?M4 : category ?M2`. 
There are no local instances. So, it tries to use the global ones. The first one is `opposite`, but opposite just creates another problem of the form `category ?M_i`, and the system loops. 

I will change the `check` command. I will "erase" the binder annotations when creating the closure. That is, the `check` above will be syntax sugar for

```
check λ (obC obD : Type) (C : category obC) (D : category obD) (F : functor C D) 
            (a b : obC) (f : @mor obC C a b), F f
```

**Comment by fpvandoorn** [comment]
So maybe we want to raise a warning or an error when someone tries to define an instance of type `A` using type `A`? (or maybe even if someone creates a cycle of instances?)

However, I think there's also something strange here with coercions. Even if I remove that `opposite` is an instance and I write

```
check λ (obC obD : Type) (C : category obC) (D : category obD) (F : functor C D) 
        (a b : obC) (f : mor a b), F f
```

I still get the error that `F` is coerced to the wrong thing.

**Comment by leodemoura** [comment]
> So maybe we want to raise a warning or an error when someone tries to define an instance of type A using type A? (or maybe even if someone creates a cycle of instances?)

We want to add an "execution tracer" for the class-instance resolution (see #72).
It will help a lot to diagnose this kind of problem.

> I still get the error that F is coerced to the wrong thing.

I know, I'm still working on it.

**Comment by leodemoura** [comment]
Fixed :-)
https://github.com/leanprover/lean/commit/4b51d50ad46e7e86efe460d95d99584d12519bd7

BTW, I tried your latest changes on top of Jeremy's changes.  I think `compose` looks really nice with the coercions. I used the notation C ⇒ D for (functor C D) just for fun. Feel free to remove it.

```
definition compose {obC obD obE : Type} {C : category obC} {D : category obD} {E : category obE}
     (F : C ⇒ D) (G : D ⇒ E) : C ⇒ E :=
functor.mk C E
    (λx, G (F x))
    (λ a b f, G (F f))
    (λ a, calc
      G (F (ID a)) = G id : {respect_id F}
               ... = id   : respect_id G)
    (λ a b c f g, calc
      G (F (g ∘ f)) = G (F g ∘ F f)     : {respect_comp F}
                ... = G (F g) ∘ G (F f) : respect_comp G)
```

**Comment by fpvandoorn** [comment]
Yes, that looks very good! The notation is also nice, I should try some similar notation for morphisms :-)
