### ISSUE TITLE
lean-mode: big error messages

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#205]
Jeremy reported the following problem

o For really big error messages with complicated expressions, it is annoying that the error message window doesn't break lines, and there is no way to scroll the window horizontally, other than moving the cursor to the end of the line. (When the error message is too big, there seems to be no way to get it to appear in the status line at the bottom, so the only way to see the error is to open the error window.)

**Comment by soonhokong** [comment]
I think this is a duplicate of #28. We have a lean customization variable `lean-default-pp-width` (default = 120) to specify pretty-print width. @avigad, could add something like the following in your emacs setup and see whether it solves the problem?

``` elisp
(setq lean-default-pp-width 80)
```

**Comment by avigad** [comment]
Yes, that seems to work well.

On a related issue: from the Lean menu, I chose "customize lean-mode". I see the option "Lean Default Pp Width", but when I click the triangle to the left of it, the option disappears. The _messages_ buffer says

  widget-apply: Symbol's function definition is void: nil

**Comment by leodemoura** [comment]
@soonhokong I thought the width would be calculated automatically by lean-mode.
If the user did not set `lean-default-pp-width`, then lean-mode uses the error buffer width.

**Comment by soonhokong** [comment]
@avigad, I can reproduce the problem. I'll fix it soon.

@leodemoura, for lean-mode to automatically adjust the pp.width, it needs to know the width of flycheck-error window before it's even opened. Because an emacs window can be split into either vertically or horizontally depending on a user's environment and setting, it's hard to predict.. Do you have a good idea how we can achieve it?

**Comment by leodemoura** [comment]
@soonhokong I'm assuming the split is not random. 
See
http://stackoverflow.com/questions/7997590/how-to-change-the-default-split-screen-direction
http://superuser.com/questions/338689/emacs-automatically-split-frames-on-creation

**Comment by soonhokong** [comment]
@leodemoura, thanks! I'll use them.
