### ISSUE TITLE
lean-mode: auto-completion erases '@'

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#207]
Here is how to reproduce the bug:
1) Type

```
import logic
check @eq.tr
```

2) Press `TAB`, select `eq.trans`, then the `@` is gone.

**Comment by leodemoura** [comment]
@soonhokong the solution in your commit only works for this instance of the problem. That is, the prefix is `@`.  I think we should fix the problem once an for all. We should implement in emacs a procedure for detecting the boundaries of Lean identifiers precisely. See the predicates `is_id_first` (valid first character for identifiers) and `is_id_rest` (valid non-first characters for identifiers).

https://github.com/leanprover/lean/blob/master/src/frontends/lean/scanner.cpp#L336
https://github.com/leanprover/lean/blob/master/src/frontends/lean/scanner.cpp#L343

**Comment by soonhokong** [comment]
@leodemoura, I see. I'll fix it.
