### ISSUE TITLE
Type changes to Prop

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#208]
When running the following file

```
import logic.core.eq
open eq eq_ops

definition rec_on2 {A : Type} {a a' : A} {B : Πa' : A, a = a' → Type} (H1 : a = a') (H2 : B a (refl a)) : B a' H1 :=
eq.rec (λH1 : a = a, id_refl H1⁻¹ ▸ H2) H1 H1

check @rec_on2
```

The type of `B` in `rec_on2` is changed by Lean to `Πa' : A, a = a' → Prop`, because I use `subst` in the proof, which only works if `B` is in `Prop`. But we don't want that the proof changes the type of the theorem, right? So it would be better if Lean raises an error since I'm proving something different (only for a special case for B).

Second question: I fixed the proof:

```
  definition rec_on {A : Type} {a a' : A} {B : Πa' : A, a = a' → Type} (H1 : a = a') (H2 : B a (refl a)) : B a' H1 :=
  eq.rec (λH1 : a = a, show B a H1, from H2) H1 H1
```

Shall I let this definition replace the current `rec_on`? I think this is useful, since some theorems which rely on `eq.rec_on` are now often of the form

```
theorem foo (...) (H : a = b) (...) :=
eq_rec H (λ(H : a = a), (...)) H (...)
```

So `eq_rec` gets `H` as argument twice, which is a bit ugly, but more importantly, if other variables depend on `H` (for example with casts), then it's easier to work with `refl a` than with `H : a = a` (even if these are definitionally equal; the elaborator usually doesn't simplify expressions like `eq.rec _ H`, while it does simplify `eq.rec_on _ (refl a)`)

**Comment by leodemoura** [comment]
@fpvandoorn this is an important issue. It is not clear what the "solution" should be.
By default, when we type `Type`, we are really typing `Type.{?m}`, and we are asking Lean to fill `?m`.
Lean will propagate constraints and instantiate `?m`. Sometimes the `?m` computed by Lean is not the one we want, and it can't be. So, how to detect this issue in general?
In your example, it is clear `?m = 0` is not the solution we want. Suppose, Lean has assigned it to `?m = 1`, it is still not the one we want, should we generate a warning too? What if `?m` is assigned to `l+1`?
There many cases to consider. Another example is a definition that contains `{A : Type} {B : Type}`, and Lean produces `{A : Type.{l}} {B : Type.{l}}`. That is, Lean is restricting `A` and `B` to be in the same universe. Should we tell the user when this happens?
This happens all the time in our files.

**Comment by leodemoura** [comment]
Regarding

> Shall I let this definition replace the current rec_on? I think this is useful, since some theorems which rely on eq.rec_on are now often of the form
> theorem foo (...) (H : a = b) (...) :=
> eq_rec H (λ(H : a = a), (...)) H (...)

I think this is a good change.

**Comment by fpvandoorn** [comment]
I see your point. There is no good uniform solution. Maybe raise an error when one occurrence of `Type` is required to be at a specific level?
For example, when we write `(A : Type) (B : Type)` as abbreviation for `(A : Type.{?m}) (B : Type.{?n})` and the constraints give us

```
?m = 0 -- raise error
?m = 7 -- raise error
?m = ?n -- don't raise error, both still can be anything (but not independently)
?m = succ ?n -- don't raise error
```

We don't want to inform the user when two universe levels must be the same, because I assume that indeed happens all over the place.

Is that reasonable?

**Comment by leodemoura** [comment]
> We don't want to inform the user when two universe levels must be the same, because I assume that indeed happens all over the place.

Yes, it does.

> Is that reasonable?

We can try. The only one I'm sure about is `?m = 0 -- raise error` since we have a name for it (`Prop`).
If the system infers `?m = 1`, then the user would have to type `Type.{1}` to get rid of the error message.

**Comment by avigad** [comment]
I like the proposed change to eq_rec. It is closer to the J-rule, i.e. the
elimination for path to type.

---

protected definition induction_on {A : Type} {a b : A} (p : a ≈ b)
  {C : Π (b : A) (p : a ≈ b), Type} (H : C a (idpath a)) : C b p :=
path.rec H p

---

Maybe that should be named path.rec_on instead of path.induction_on?

Regarding the other issue, I think in most cases the statement of the
theorem will dictate the constraints on the universes.

Maybe the right thing to do is to issue a warning when the proof imposes
constraints beyond what is imposed by the statement of the theorem? The
user could change a setting to determine whether this is given a warning,
an error, or nothing.

Jeremy

**Comment by leodemoura** [comment]
> The user could change a setting to determine whether this is given a warning,
> an error, or nothing.

I like this.

**Comment by avigad** [comment]
I guess the key point is that there are two things that can happen: the statement of the theorem might impose more constraints than the user indicated, and the proof itself might impose more constraints.

Both are things a user might want to be warned about, but the second seems to be a bigger violation than the first.

**Comment by leodemoura** [comment]
> Both are things a user might want to be warned about, but the second seems to be a bigger violation than the first.

I have changed that a few weeks ago. The statement/type of the theorem is elaborated independently of the proof. When, we elaborate the proof, we cannot change the type anymore. So, at least, this problem we don't have anymore.

**Comment by leodemoura** [comment]
So far, I added the infrastructure for perform this kind of validation.
However, I'm currently reporting an error only when the elaborator makes a `Type` into a `Prop`.
I will add configuration options to control when errors/warnings are reported later.
BTW, our library had only one violation.
