### ISSUE TITLE
bug when C-c C-f gives implicit arguments

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#209]
I had some strange behavior in my version of eq.lean:

https://github.com/fpvandoorn/lean/blob/master/library/logic/core/eq.lean#L134

Steps to reproduce:
1: Compile the file (C-c C-x)
2: Let lean-server(?) infer the blank (C-c C-f) in line 134. Note that it does not give implicit argument to any term
3: Compile the file again
4: Replace the term from step 2 back to a blank.
5: Replace the blank again by a term with C-c C-f. Note that `congr_arg2_dep` now gets implicit arguments. Also, the current term is invalid, since `congr_arg2_dep` is not prefixed by `@`.

So there are 1 or 2 issues here:
- when a term gets implicit arguments, it should be prefixed by `@`
- (maybe not an issue) the term given by C-c C-f is different in step 2 and step 5.

**Comment by leodemoura** [comment]
I managed to reproduce the problem. I will fix it.
