### ISSUE TITLE
implicit arguments for inductive constructor

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#210]
I'm not sure whether the following is intended or not, but it feels strange.

The definition of a natural transformation is

```
inductive natural_transformation {obC obD : Type} {C : category obC} {D : category obD}
    (F G : functor C D) : Type :=
mk : Π (η : Π(a : obC), mor (object F a) (object G a)), (Π{a b : obC} (f : mor a b), morphism G f ∘ η a = η b ∘ morphism F f)
 → natural_transformation F G
```

Now the type of `natural_transformation.mk` is

```
natural_transformation.mk :
  Π {obC : Type} {obD : Type} {C : category obC} {D : category obD} {F G : functor C D}
  (η : Π (a : obC), mor (F a) (G a)),
    (∀ {a b : obC} (f : mor a b), eq (compose (G f) (η a)) (compose (η b) (F f))) → natural_transformation F G
```

Note that `F` and `G` are implicit here. Is this intended? It feels strange, because the constructor `functor.mk` of `functor` has `C` and `D` as explicit arguments

```
inductive functor {obC obD : Type} (C : category obC) (D : category obD) : Type :=
mk : Π (obF : obC → obD) (morF : Π⦃A B : obC⦄, mor A B → mor (obF A) (obF B)),
    (Π ⦃A : obC⦄, morF (ID A) = ID (obF A)) →
    (Π ⦃A B C : obC⦄ {f : mor A B} {g : mor B C}, morF (g ∘ f) = morF g ∘ morF f) →
     functor C D


functor.mk :
  Π {obC : Type} {obD : Type} (C : category obC) (D : category obD) (obF : obC → obD)
  (morF : Π ⦃A B : obC⦄, mor A B → mor (obF A) (obF B)),
    (∀ ⦃A : obC⦄, eq (morF (ID A)) (ID (obF A))) →
    (∀ ⦃A B C_1 : obC⦄ {f : mor A B} {g : mor B C_1}, eq (morF (compose g f)) (compose (morF g) (morF f))) →
    functor C D
```

**Comment by leodemoura** [comment]
I will take a look. `F` and `G` should be explicit since they occur in other arguments.
Is this declaration in your private repository?

**Comment by fpvandoorn** [comment]
[Yes](https://github.com/fpvandoorn/lean/blob/master/library/algebra/category.lean#L298)

**Comment by leodemoura** [comment]
@fpvandoorn I analyzed this issue. This is not a bug. This is the intended behavior.
Any datatype parameter is marked as implicit in an introduction rule if the parameter occurs in the type of another argument. This is the case for `F` and `G` since they occur in the type `η`.
We rely on this behavior in many examples. For example, when we define the `list A`, we don't provide `A` to `cons`.
We have an even more relaxed mode, where all parameters are marked implicit. We trigger the relaxed mode by adding '{}' after the introduction rule name. Example: `nil` in `list A`. 

I realize that both behaviors are not ideal for the `natural_transformation` datatype. 
One possibility is to add a new `strict` mode, where Lean will _not_ mark additional arguments as implicit.
What do you think?

**Comment by fpvandoorn** [comment]
This sounds like good behavior. Usually you can infer a parameter when it is used in the type. But there are examples where you want to force such a parameter to be explicit, for example if you have a parameter `p : A × B` and only `pr1 p` occurs in the type. So adding some strict mode sounds good. Maybe with syntax `()` similar to `{}` (and then for completeness we could add `⦃⦄`).

By the way, why are `C` and `D` explicit in `functor.mk`? They occur all over its type as implicit arguments (to `mor` and `ID`). That sounds good enough to me to have them also implicit in the constructor, in general (in this case, I'm don't know whether I want them implicit).

**Comment by leodemoura** [comment]
> Maybe with syntax () similar to {} (and then for completeness we could add ⦃⦄).

Good. I will use this syntax.

> By the way, why are C and D explicit in functor.mk?
> They occur all over its type as implicit arguments (to mor and ID). 

The implicit annotations are inferred before we elaborate the types.
So, `C` and `D` don't "occur" at `functor.mk` at this time.
We can move this step after elaboration.

**Comment by fpvandoorn** [comment]
> The implicit annotations are inferred before we elaborate the types.
> So, C and D don't "occur" at functor.mk at this time.
> We can move this step after elaboration.

I think that would be good. An implicit occurrence of some variable sounds like an equally good (or even better) reason to mark it as an implicit argument.
