### ISSUE TITLE
script for creating installation packages for Windows and OSX

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#221]
For Windows we need two packages: fat and lean.
Both of them should contain:
1- lean, standard library (.lean, TAGS, .olean)
2- ninja, linja
3- lean-mode, and all .el dependencies
4- all required .dlls

The "fat" version also should contain Emacs, and any other dependency.
The "fat" version should work on an empty machine with minimal/no user help.

**Comment by soonhokong** [comment]
64bit emacs-24.4 for Windows: http://sourceforge.net/projects/emacsbinw64/files/snapshot/emacs-bin-w64-20141001.7z/download

**Comment by soonhokong** [comment]
http://www.pyinstaller.org

**Comment by leodemoura** [comment]
apt-get for windows:
https://chocolatey.org/

**Comment by soonhokong** [comment]
I have tried [chocolatey](https://chocolatey.org/), my impression was that it's a collection of existing windows installers. I am not sure that it can replace something like msys2 or cygwin..

**Comment by leodemoura** [comment]
I found it installing the Atom editor.

**Comment by soonhokong** [comment]
> I found it installing the Atom editor.

:smile:  Please share your opinion about it.

**Comment by leodemoura** [comment]
I didn't use it much. So far, nothing there impressed me.
I think there are still under heavy development. I think it is too early to use it.
