### ISSUE TITLE
wrong pp highlighting

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#225]
pretty printer doesn't highlight name when pp.universes or pp.implicit is on.

```
import standard
check prod
set_option pp.universes true
check prod
set_option pp.universes false
check and.comm
set_option pp.implicit true
check and.comm
```

**Comment by leodemoura** [comment]
I can reproduce this behavior. I don't think the highlight is coming from `lean-mode`, but from `compilation-mode`. The highlight is accidental. We will figure out a way to tell emacs it should not highlight the lean term.

**Comment by leodemoura** [comment]
@soonhokong The spurious highlight is produced by regular expressions stored at `'compilation-mode-font-lock-keywords`.  I fixed the problem by adding the following line to `lean-mode.el`.

```
(set 'compilation-mode-font-lock-keywords '())
```

I'm assuming it only affects the lean-mode buffers. Is that correct?
