### ISSUE TITLE
lean-mode: missing type information

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#226]
Reported by Floris:

Unfortunately, it just happened to me again. I was working on this file:
https://github.com/fpvandoorn/lean/blob/master/library/algebra/category/limit.lean
I had the following faulty definition

```
  definition constant_diagram (a : ob) : I ⇒ C :=
  functor.mk (λ i, a)
        (λ i j u, id)
        (λ i, rfl)
        (λ i j k v u, !id_compose)
  end
```

then I replaced "!id_compose" by "sorry" to see the type of the term I had to prove. Then compiling works fine, but then hovering over subterms of the proof doesn't display anything in the minibuffer (if I hover over a symbol in `functor.mk (λ i, a)` I do get the correct type, but any type later than that does not display). Actually, after executing M-x lean-server-restart-process, and even after restarting emacs, it still doesn't display... I'm not sure what's going on here.

**Comment by leodemoura** [comment]
@soonhokong The problem is that the file contains `TAB`s. For lean, each `TAB` counts as one character, but for emacs it depends on the user `TAB` size. 

```
-- TYPE|17|20
eq id (compose id id)
-- ACK
-- SYMBOL|17|20
sorry
-- ACK
```

**Comment by fpvandoorn** [comment]
Apparently there is some hook somewhere which replaces 8 spaces by a TAB whenever I save the file. However, this happens only in certain (but not all) .lean files. I have nothing related to tabs in my ~/.emacs file (as far as I can see). Is it possible that lean-mode does this?

**Comment by soonhokong** [comment]
>  Is it possible that lean-mode does this?

To my knowledge, no. @leodemoura, have you experienced something like this?

There is an emacs function `tabify` and `untabify` which convert space to <kbd>TAB</kbd>s and vice versa.

```
http://www.pement.org/emacs_tabs.htm
```

It's possible that you have `tabify` function somewhere in your configuration directly or indirectly..

**Comment by soonhokong** [comment]
Personally, I think it's best to avoid the use of tabs, especially in library files. However, I think `lean-mode` should work with <kbd>TAB</kbd>s. I'm working on a fix.

**Comment by leodemoura** [comment]
> To my knowledge, no. @leodemoura, have you experienced something like this?

No, I haven't. However, my .emacs file contains

```
(setq-default indent-tabs-mode nil)
```

**Comment by fpvandoorn** [comment]
A late follow-up: I have found the culprit which changed 8 spaces to tabs when saving. The minor mode `WSC` calls `whitespace-cleanup` on save, and if your configuration is "wrong" (`whitespace-style` contains `indentation`) then 8 spaces are replaced by tabs.

If Lean calls the minor mode WSC we might want to change the default behavior (I assume that what I described is the default behavior, because AFAIK I didn't change anything previously)

**Comment by soonhokong** [comment]
@fpvandoorn, thanks a lot for the investigation. I think we don't really need the package. Let me remove it soon.

**Comment by fpvandoorn** [comment]
Don't we use it to delete trailing whitespace when saving?

**Comment by soonhokong** [comment]
I think it was an over-kill to use the mode. emacs already provides `whitespace-cleanup` function and I'm thinking about using it this time. The behavior depends on other variables and the item 3 in [this article](http://batsov.com/articles/2011/11/25/emacs-tip-number-3-whitespace-cleanup) explains the behavior that you had.

**Comment by fpvandoorn** [comment]
Ok, sounds good.

**Comment by leodemoura** [comment]
@soonhokong Some users like TABs. Lean-mode should work even when the buffer contains `TAB`s.
I see the following possible solutions:
1- Add a `--tab-width=size` to Lean. Lean-mode would use it to tell Lean the tab-size being used in Emacs. Lean would only use this information to produce column numbers. 
This is a bit hackish.

2- Lean-mode adjusts the column numbers bases on the tab-width being used. This one is a cleaner solution because it would work even if the user changes the `TAB` size after `lean --server` processed the buffer.

**Comment by soonhokong** [comment]
Dear @leodemoura,

> Some users like TABs. Lean-mode should work even when the buffer contains TABs.

This is already the case. When lean-mode passes column-number to lean-server, it actually passes **byte-offset** from the beginning of the line. As far as I understand, that is also how Lean-server interprets column-number.

I agree that we should not make it the default option to remove 'tabs' from Users' file. The plan is to make it optional so that one can use it conveniently.

**Comment by leodemoura** [comment]
> As far as I understand, that is also how Lean-server interprets column-number.

Great!

> I agree that we should not make it the default option to remove 'tabs' from Users' file.
> The plan is to make it optional so that one can use it conveniently.

So, there is no real issue here. This is just a configuration issue.
Should we close the issue?

**Comment by soonhokong** [comment]
For now, we are relying on whitespace-cleanup-mode, which is a package. I did some google-search and found out that there is a built-in function `whitespace-cleanup` which essentially does the job. I will remove the whitespace-cleanup-mode dependency and close this issue with how to set things up.
