### ISSUE TITLE
apt-get install lean: invalid header

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#229]
When we install lean using

```
sudo apt-get install lean
```

and type

```
lean --help
```

We get

```
Lean (version 0.2, commit GITDIR-NOTFO, Release)
```

I believe there is no commit number because Lean was built at Ubuntu's servers.
We should take this scenario into account in our cmake file

**Comment by leodemoura** [comment]
It would be cool if we could include the Ubuntu version like gcc :-)

```
% g++ --version
g++ (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1
```

**Comment by soonhokong** [comment]
For now, I made a small fix to take the git commit shasum away when it's not available.

> It would be cool if we could include the Ubuntu version like gcc :-)

I think so. We need to show the package version at launchpad (i.e. 0.2.0~ubuntu1~12.04).

**Comment by soonhokong** [comment]
1) When git sha1 is available:

```
Lean (version 0.2.0, commit 4a119a0, Release)
```

2) When git sha1 is not available, but there is bin/package_version file

```
Lean (version 0.2.0, package 0.2.0~ubuntu1~12.04, Release)
```

3) Git sha1 is not available, bin/package_version does not exist.

```
Lean (version 0.2.0, Release)
```

**Comment by leodemoura** [comment]
Really cool! :100:
