### ISSUE TITLE
don't create .d file when there is an error

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#23]
E.g. make produced the following "congr.d":

---

/home/jeremy/projects/lean/library/standard/logic/classes/congr.olean : /home/jeremy/projects/lean/library/standard/logic/classes/cong
r.lean /home/jeremy/projects/lean/library/standard/logic/classes/congr.d error: file 'logic/connectives/function' not found in the LEA
N_PATH

---

Then make produced the following error message:

 /home/jeremy/projects/lean/library/standard/logic/classes/congr.d:1: **\* multiple target patterns.  Stop.

Instead, the first failure should raise the error and not produce the .d file.

**Comment by soonhokong** [comment]
I reported a similar problem with `.olean` file to @leodemoura.

**Comment by leodemoura** [comment]
I submitted a fix for this problem and related ones.
