### ISSUE TITLE
refresh-packages slows emacs startup

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#233]
The line

```
(package-refresh-contents)
```

in .emacs slows down emacs startup by a couple of seconds. I find it convenient to comment it out. Should the documentation suggest this trick to users? Or maybe lean-mode should try refreshing package contents only if some of the required packages are absent?

**Comment by soonhokong** [comment]
Yes, this makes the start-up slow.

I'll make a change so that `(package-refresh-contents)` is called only if there are missing packages for Lean and we need to install something.
