### ISSUE TITLE
allow opening namespace inside section

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#236]
Is there still a reason why namespaces cannot be opened inside a section? I asked this before (by e-mail, subject "RE: namespace management", Sep 5), and the response that this was problematic since some things, like notation, were transient in sections. In the meantime, this behavior for transient notation has been changed, so I'll request this again. 

I think this would be really useful. In a file you might be working with the same parameters/variables, but want to organize different subjects in different namespaces.

**Comment by leodemoura** [comment]
@fpvandoorn There are issues. First, not every notation declaration is supported in sections.
See the following auxiliary procedure:
https://github.com/leanprover/lean/blob/master/src/frontends/lean/notation_cmd.cpp#L58
It "erases" references to section parameters that are implicit.
This is hackish, but allows us to define useful notation inside sections.
BTW, we now have `variables`. Perhaps, we should remove this hack. That is, notation cannot contain section parameters. In most cases we can use `variables` anyway.

Another problem is that we would have to support scenarios such as:

```
section 
   parameter A : Type
   namespace foo
        definition bla (a : A) := ...
   end foo
   ...
   open foo
   -- bla would have to be an alias for `foo.bla A`
   ...
end 
```

There are more issues I'm not listing here. The general "theme" is that we can open namespaces, namespaces group many different kinds of objects. 
Sorry for being negative, but we are super behind schedule with the implementation.

**Comment by fpvandoorn** [comment]
Okay, that's fine. I can structure the namespaces around sections.

By the way, I think it is useful that notation can contain section parameters. I'm using it in `category.basic` where I define notation for composition and other things, depending on the parameter `C`.
