### ISSUE TITLE
instances are not imported

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#239]
I don't know whether this is a bug or whether I'm doing something work, but when I write (in my repository / after the pull request has been merged)

```
import algebra.category.constructions

open category.ops

definition foo {obC : Type} (C : category obC) : C × C ⇒ C × C := functor.id
definition bar {obC : Type} (C : category obC) : type ⇒ type := functor.id
```

I get as error that it cannot synthesize a term of type `category (prod obC obC)` and `category Type`. However, I've defined these categories as instances in namespace `category.ops`

```
instance category_of_categories type_category category_one product.prod_category
```

(putting the definitions right below that line in `constructions.lean` does work)

**Comment by leodemoura** [comment]
The following commands may be useful

```
print classes 
print "----- instances -----"
print instances category
```

**Comment by fpvandoorn** [comment]
Ok, thanks.

It looks like the `instance` command does not export to other files. If I write a file `test.lean`

```
import logic.decidable
definition bar1 : decidable true := decidable.inl trivial
definition bar2 [instance] : decidable true := decidable.inl trivial
instance bar1
```

and then another file

```
import .test
print instances decidable
```

Then only `bar2` is an instance, `bar1` isn't.

**Comment by leodemoura** [comment]
Sorry... I know what is going on.
A couple of weeks ago, @soonhokong and I changed the semantics of commands such as `reducible`, `instance`, etc. That is, commands that have a `[...]` associated modifier.

These commands are not persistent by default. The idea was to allow users to make quick modifications that are discarded in the end of the file.
To make their effect persistent, we have to write

```
instance [persistent] bar1
reducible [persistent] bar1
```

We forgot to tell you and Jeremy about that.

**Comment by fpvandoorn** [comment]
Ok, that makes sense. So this is not a bug.
