### ISSUE TITLE
Flycheck gives strange output

### ISSUE THREAD

**Issue by javra** [leanprover/lean#241]
I played around with Floris' library/algebra/category/basic.lean. When after his definition of hom inside the category namespace I type in "check hom" the output gives me "hom : category ob" while I guess it should be "hom : ob → ob → Type"? "check (@hom)" gives the desired output.

**Comment by leodemoura** [comment]
We need to fix that. The bug is triggered because inside of the section `hom` means `hom ob C`.
The system is actually showing the type of `C` instead of `hom ob C`.
