### ISSUE TITLE
parser error?

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#242]
When I write the following definition to the _bottom_ of the file `algebra.category.basic`,

```
definition MK a b c d e f g : Category := 
Category.mk a (category.mk b c d e f g)
```

I get an error in the definition of `category` in the _top_ of the file.

It might be a parser error; if I write

```
definition MK (a) (b) (c) (d) (e) (f) (g) : Category := 
Category.mk a (category.mk b c d e f g)
```

or 

```
definition MK (a b c d e f g) : Category := 
Category.mk a (category.mk b c d e f g)
```

it is accepted.

**Comment by leodemoura** [comment]
It is parsing as 

```
definition MK (a b c d e f g : Category) : _ := ...
```

instead of

```
definition MK (a b c d e f g : _) : Category := ...
```

It is ambiguous. I think in most cases, users expect the second interpretation. I will change it.

The error message is also "crazy". I will try to improve it.
