### ISSUE TITLE
add an option to copy type information

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#245]
@avigad suggested.

**Comment by soonhokong** [comment]
lean-mode saves the displayed type information message into kill-ring, which can be accessed by yank <kbd>C-y</kbd> command if
- a customization option `lean-show-type-add-to-kill-ring` is non-nil _and_
- a user runs `lean-show-type` by explicitly typing <kbd>C-c C-t</kbd>

Note that getting type information by moving cursor on an identifier does not save any information to kill-ring even if `lean-show-type-add-kill-ring` is non-nil.

**Comment by avigad** [comment]
Excellent. I came across another case where the type information (with
implicit arguments turned on) was too big -- emacs clipped the information
buffer at 6 lines or so. This will help there too.
