### ISSUE TITLE
Don't allow "!" as operator symbol

### ISSUE THREAD

**Issue by javra** [leanprover/lean#248]
Currently importing hott.trunc makes the "make all arguments implicit" operator unusable since it seems to overwrite the "!" by defining its own prefix operator with that name. Maybe such operator shouldn't be allowed. (Or is the the definition of "!" as "make all arguments implicit" operator also done in "user namespace"?)

**Comment by leodemoura** [comment]
Yes, we should not allow the user to use use `!` as an operator. Same for `@`.

**Comment by avigad** [comment]
We also use "@" for path concatenation. Maybe we should change that to
"++", as for lists?

On Tue, Oct 21, 2014 at 1:43 PM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
> Maybe we should change that to "++", as for lists?

I agree.

**Comment by javra** [comment]
What about \cdot? Or do we want to save that one for algebraic operations?

2014-10-21 17:16 GMT-04:00 Leonardo de Moura notifications@github.com:

**Comment by leodemoura** [comment]
Where are we using \cdot?

**Comment by javra** [comment]
It was meant as an alternative proposition on how to denote path
concatenation, maybe '++' is a bit "wide"... especially if we then name the
"parallel composition" of paths '+++'

2014-10-21 18:45 GMT-04:00 Leonardo de Moura notifications@github.com:

**Comment by leodemoura** [comment]
I see. 
BTW, I submitted a commit that forbids `!` and `@` in notation declarations.
I used \tr for path concatenation like in the HoTT book.

**Comment by leodemoura** [comment]
Feel free to change `\tr` to something else.

**Comment by javra** [comment]
I noticed that \tr is now right associative. Don't we prefer left
associativity? Or is it considered bad style to not add the respective
parentheses?

2014-10-21 19:41 GMT-04:00 Leonardo de Moura notifications@github.com:

**Comment by leodemoura** [comment]
> I noticed that \tr is now right associative. Don't we prefer left
> associativity?

I move it back to left.
