### ISSUE TITLE
output convention for type info

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#25]
Can we change the output convention for type information?
- Option name: `--typeinfo`
- `--typeinfo` takes an optional argument `--typeinfo <LINE_NO>`: If `LINE_NO` is specified, lean only reports type information at the specified line `LINE_NO`, otherwise it reports all type information in a file.
- Message format: use `|` as a delimiter. Note that <TYPE_OF_ID> doesn't have a newline `\n`in it

```
TYPE|<FILENAME>|<LINE_NO>|<COL>|<TYPE_OF_ID>
```

Example:

```
TYPE|/home/soonhok/work/lean/library/standard/logic/connectives/basic.lean|154|69|(a → b) → (b → a) → and (a → b) (b → a)
TYPE|/home/soonhok/work/lean/library/standard/logic/connectives/basic.lean|154|79|a → b
TYPE|/home/soonhok/work/lean/library/standard/logic/connectives/basic.lean|154|82|b → a
```

**Comment by leodemoura** [comment]
Let's talk tomorrow. We should define the protocol between Lean and your tool. 
BTW, the types can be quite big, we may need multiple lines to display them.

**Comment by soonhokong** [comment]
For the record, here is the protocol: https://github.com/leodemoura/lean/blob/master/doc/server.org
