### ISSUE TITLE
another segfault

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#253]
I get a segfault when compiling this file:

https://github.com/fpvandoorn/lean/blob/fully_bundled/library/algebra/category/functor.lean#L104

It has something to do with the argument (and probably the `sorry`)

```
(Hmor : ∀a b (f : a ⟶ b), eq.rec_on sorry homF a b f = homG a b f)
```

on line 104.

**Comment by leodemoura** [comment]
The segfault is due to a stackoverflow. 
I fixed that. It was generated because Lean entered in an infinite loop trying to solve this elaboration problem. 

BTW, I believe there is a typo in your file. I think it should be

```
(Hmor : ∀a b (f : a ⟶ b), eq.rec_on sorry (homF a b f) = homG a b f)
```

instead of 

```
(Hmor : ∀a b (f : a ⟶ b), eq.rec_on sorry homF a b f = homG a b f)
```

right?
