### ISSUE TITLE
automatically add `no_confusion` construction for inductive types

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#256]

**Comment by leodemoura** [comment]
The idea is to automate the manual constructions such as:

https://github.com/leanprover/lean/blob/49941ce35b953855588d97b95285aa63a600ec67/tests/lean/run/sigma_no_confusion.lean

https://github.com/leanprover/lean/blob/49941ce35b953855588d97b95285aa63a600ec67/tests/lean/run/tree.lean

https://github.com/leanprover/lean/blob/49941ce35b953855588d97b95285aa63a600ec67/tests/lean/run/vector.lean

**Comment by leodemoura** [comment]
Closed by commits
- e8bc0f82493d297903878e5409dc928cafc33a6c
- b5da143fc09fbd55337a90d247130999e6418ae7

**Comment by fpvandoorn** [comment]
So these constructions help to prove the `injectivity` and `discriminate` tactics in Coq? (`injectivity` states that the constructors of an inductive type are injective, and `discriminate` says that the images of different constructors are disjoint). Will proofs for those statements also be automatically generated, later?

**Comment by leodemoura** [comment]
Yes. We can now simulate both of them. Some remarks:
1- It is not a tactic like in Coq. So, we can use it in "declarative mode" too.
2- We can also use it in tactic mode. However, instead of having a hard-coded tactic, we just write
    `
    apply (no_confusion H) 
`
