### ISSUE TITLE
lean-mode: visualize `-- PROOF_STATE` info

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#259]
The new `PROOF_STATE` info is generated when we are using tactics.
When we are using the `begin ... end` construct. See 
https://github.com/leanprover/lean/blob/master/tests/lean/run/beginend2.lean

The `-- PROOF_STATE` info is associated with each `comma` in the sequence.
The format is 

```
-- PROOF_STATE|[line-num]|[col-num]
[goal]
-- ACK
```

**Comment by soonhokong** [comment]
@leodemoura, we need to support a case where we have multiple goals as we discussed. Could you extend the syntax as follows?

```
-- PROOF_STATE|[line-num]|[col-num]
[goal_1]
--
[goal_2]
--
...
--
[goal_n]
-- ACK
```
