### ISSUE TITLE
add pygments lexer for lean

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#26]
We can implement a pygments lexer for Lean and make a pull request as Agda and Idris people did:
- Agda: https://bitbucket.org/birkenfeld/pygments-main/pull-request/203/add-literate-agda-lexer/diff
- idris: https://bitbucket.org/birkenfeld/pygments-main/pull-request/210/idris-lexer-added-lexer-for-idris/diff

Github will eventually pick a new version of pygments and use it.

**Comment by leodemoura** [comment]
Added pull request to pygments
https://bitbucket.org/birkenfeld/pygments-main/pull-request/397/lean-lexer-add-lexer-for-lean-theorem/diff

**Comment by leodemoura** [comment]
Lean lexer has been merged
https://bitbucket.org/birkenfeld/pygments-main/commits/c494f7027b628eabbebd02573799b7ac92770f7f?at=default

**Comment by soonhokong** [comment]
Great!

FYI, the current release is 1.6 and the next version (2.0) will support Lean:

https://bitbucket.org/birkenfeld/pygments-main/src/tip/CHANGES
