### ISSUE TITLE
better notation for `proof-qed` expressions

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#271]
We are using `proof ... qed` to postpone the elaboration of some expression.
The name is bad since we want to be able to postpone the elaboration of arbitrary expressions not just proofs. @avigad noticed this issue when formalizing semi-simplicial sets in Lean.
We need a better notation for `proof ... qed` expressions.
Remark: `begin ... end` is already been used for blocks of tactics.

**Comment by leodemoura** [comment]
@avigad any suggestions?
@fpvandoorn does this issue bother you?

**Comment by fpvandoorn** [comment]
`proof ... qed` is indeed a bit weird for definitions. 
I like none of the following suggestions very much, but I couldn't think of something better:
Maybe `block ... end`? 
Or `define ... end`? 
Or maybe rename the current `begin ... end` to `tactic ... end`?

Also, I have hardly used `proof ... qed` so far. I've tried it a couple of times, but  sometimes with unexpected results. Can you explain why the following doesn't work? The definition in the `algebra.category.constructions` is the same, but without `proof ... qed`. However, replacing `proof ... qed` by `sorry` will compile easily, so the elaborator can figure out the type of what is proven, and the actual proof term is not used anywhere else in the definition.

```
  definition postcomposition_functor {x y : D} (h : x ⟶ y) 
      : Slice_category D x ⇒ Slice_category D y :=
  functor.mk (λ a, dpair (to_ob a) (h ∘ ob_hom a))
             (λ a b f, dpair (hom_hom f)
       (proof calc
         (h ∘ ob_hom b) ∘ hom_hom f = h ∘ (ob_hom b ∘ hom_hom f) : assoc h (ob_hom b) (hom_hom f)⁻¹
           ... = h ∘ ob_hom a : congr_arg (λx, h ∘ x) (commute f) qed))
             (λ a, rfl)
             (λ a b c g f, dpair_eq rfl !proof_irrel)
```

(sorry for derailing the issue, feel free to answer anywhere else)

**Comment by leodemoura** [comment]
> Can you explain why the following doesn't work? 

I will investigate. It takes several hours to understand what is going on.

I noticed it fails even if we use `proof sorry qed`. 
The proof qed gets executed and returns the control to the main elaborator. 
The main elaborator "diverges" when it tries to process the solution produced in the proof-qed block.
This is what I managed to figure out so far.

**Comment by avigad** [comment]
How about "do ... end" for tactic blocks, and "begin ... end" for
definitions?

I sometimes find "proof ... qed" useful in situations where I am getting an
unhelpful error message. Adding it can help localize the problem and
produce a better error message. I think it will be especially useful for
very long proofs.
