### ISSUE TITLE
lean-mode: line wrapping in error messages

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#28]
Currently goals are not pretty-printed, and extend beyond the end of the flycheck error window. (However, when the cursor is on the location, the goal is also displayed at information line at the bottom, which is longer.)

There are three issues here:

(1) goals should be displayed better

(2) the flycheck - lean interface should exchange information about line width

(3) some information (like goals) can appear in different contexts - in the error window, in the information line, and even in a popup - and different formatting is needed for each

**Comment by soonhokong** [comment]
- @avigad, do you think (1) and (3) are still issues for now? 
- @leodemoura, can we extend the `--flycheck` option to take an unsigned int parameter specifying the pretty-print width?

**Comment by leodemoura** [comment]
We should allow users to set configuration options in the command line (at least the basic ones: bool, int and unsigned int). Perhaps, we should have `-D [option] = [value]` like cmake, gcc, etc.

**Comment by soonhokong** [comment]
@leodemoura, I like the idea. Could you implement that then? I think it's better to have another issue for that.

**Comment by leodemoura** [comment]
Ok, I will add a separate issue for it.

**Comment by leodemoura** [comment]
BTW, we can use the following workaround.
Create a `config.lean` file containing the desired `set_option` commands.
Then, include `config.lean` in the command line before the actual `.lean` file you are trying to compile.

**Comment by avigad** [comment]
I trust your judgment here -- feel free to close the issue if you would like.

**Comment by soonhokong** [comment]
I see. Once I handle the issue (2). I'll close this one. For the record, it's related with #130 and 37c36e8.

**Comment by soonhokong** [comment]
We can customize the width of error messages by changing `lean-flycheck-checker-options` customization variable. By default, it uses 120 characters.
