### ISSUE TITLE
universe levels and variables

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#282]
In the definition of cast

```
definition cast {A B : Type} (H : A = B) (a : A) : B :=
eq.rec a H
```

the universe levels of `A` and `B` are the same. However, if I replace the theorem by 

```
universe u
definition cast {A B : Type.{u}} (H : A = B) (a : A) : B :=
eq.rec a H
```

later parts of the cast library will break. What's the difference between those two definitions?

What I wanted was to add variables to that library, something like

```
universe u
variables {A B : Type.{u}}
```

Is there something else I can do to change `A` and `B` to variables?

**Comment by leodemoura** [comment]
The command 

```
universe u
```

creates a fixed universe.
So, `cast` is not universe polymorphic.
To make `cast` universe polymorphic, we should write

```
definition cast.{u} {A B : Type.{u}} (H : A = B) (a : A) : B :=
eq.rec a H
```

Or

```
universe variable u
definition cast {A B : Type.{u}} (H : A = B) (a : A) : B :=
eq.rec a H
```

**Comment by leodemoura** [comment]
There is yet another option

```
context
   universe u
   definition cast.{u} {A B : Type.{u}} (H : A = B) (a : A) : B :=
   eq.rec a H
end
```

In this case, the `u` is fixed inside the context, but `cast` is universe polymorphic outside of it.

**Comment by leodemoura** [comment]
> universe u
> variables {A B : Type.{u}}
> Is there something else I can do to change A and B to variables?

You can use

```
   universe variable u
   variables {A B : Type.{u}}
```

**Comment by fpvandoorn** [comment]
Ah, I didn't knew about the `universe variable` command. Thanks!
