### ISSUE TITLE
other symmetry proofs automatically inserted?

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#286]
In `calc`-proofs, `symm` is now automatically inserted in front of the `H_i`'s, which is really nice.
Suppose we now do a `calc` proof with - for example - `==`, where we have specified `calc_symm heq.symm`. Should `heq.symm` now also be automatically inserted? Because that currently doesn't seem to work.

Also, is there another reason to specify `calc_symm foo`? Also, what is the purpose of `calc_refl foo`? Previously (maybe only in Lean 0.1) I think

```
calc
    a = b : H1
  ... = c : H2
```

meant `trans (trans refl H1) H2`, but currently it looks like it just means `trans H1 H2`. Is there another reason where instances of `calc_refl` is used?

**Comment by leodemoura** [comment]
> Should heq.symm now also be automatically inserted? Because that currently doesn't seem to work.

It should. I will investigate the issue.

> Also, is there another reason to specify calc_symm foo?

No. It is just a hint for the `calc` expression.

> Also, what is the purpose of calc_refl foo? 

It is used for implementing the `{ H }` notation in calculational proofs.
The notation `{ H }` is shorthand for `subst H (refl LHS)`, where `LHS` is the current left-hand-side in the calculational proof.  Suppose we have

```
calc
    a = b : H1
 ...  = c : {H2}
```

It is compiled into `trans H1 (subst H2 (refl b))`
