### ISSUE TITLE
emacs configuration

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#29]
More emacs configuration could go in either the lean emacs mode or the flycheck mode. Two things that come to mind are:

(1) deleting trailing whitespace
(2) putting the error message window and compilation window to the right, by default
(3) setting the file window to 100 columns, by default

**Comment by soonhokong** [comment]
(1) and (3) are implemented in f523c25c52057db1d3dc60265471137f44e15e65
I'll close this one, but will try to find a solution for (2).
