### ISSUE TITLE
flycheck gives wrong type of notation

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#292]
In the following example:

```
import data.nat
open nat
notation `one`:max := (succ 0)
check one
```

when hovering over `one`, the displayed type is `one : ℕ → ℕ`

**Comment by leodemoura** [comment]
This is an instance of a bigger problem: how to provide type information for notation instances?
I think we can fix the atomic notation case, I will see what we can do for the general case.

BTW, we don't need the `:max` hack anymore.
It is supposed to work if we type one

```
   notation `one` := (succ 0)
```
