### ISSUE TITLE
c-c c-l in emacs interface broken

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#294]
When I type "c-c c-l" to run lean from emacs, I get this message:

---

-_\- mode: compilation; default-directory: "~/projects/lean/library/hott/" -_-
Compilation started at Wed Nov  5 09:01:48

"~/projects/lean/bin/lean" -Dpp.width=80  "/home/avigad/projects/lean/library/hott/path.lean"
/bin/bash: ~/projects/lean/bin/lean: No such file or directory

Compilation exited abnormally with code 127 at Wed Nov  5 09:01:48

---

The same happens when I use that line at the terminal. If I delete the quotation marks around "~/projects/lean/bin/lean", the command works fine.

"c-c c-l" worked fine yesterday.

**Comment by soonhokong** [comment]
Thanks for the report. I made the change yesterday to support a directory name containing spaces. I just rolled back to the previous state.

I'll do something else and test in all platforms before I push.
