### ISSUE TITLE
error when merging identical structures

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#296]
If we combine two copies of the same structure, the coercions to those structures should have different names. Currently the following example raises an error because Lean tries to create two definitions of `has_two_muls.to_has_mul`

```
structure has_two_muls [class] (A : Type) extends has_mul A renaming mul→mul1, 
                                                  has_mul A renaming mul→mul2
```

(also, you might want to add an example to the tutorial where you combine two structures _and_ rename their projections)

**Comment by leodemoura** [comment]
We can generate a better error message. Or, do you want to be able to do that?

**Comment by fpvandoorn** [comment]
It might be useful, though I can't give a straightforward example. Everything I can think of is convoluted or can be done better in an alternative way. So just improving the error message might also be good (but maybe at some point we want to allow this behavior).

**Comment by leodemoura** [comment]
It is not hard to support. I can generate `has_two_muls.to_has_mul1` and `has_two_muls.to_has_mul2`
An orthogonal issue is the ambiguity in the class-instance resolution and coercion insertion.

**Comment by leodemoura** [comment]
I added a bigger example in the tutorial. 
https://github.com/leanprover/tutorial/blob/master/structures.org
It merges an abelian group and a monoid to build a ring

The web version will be live soon:
https://leanprover.github.io/tutorial/structures.html
