### ISSUE TITLE
overloading for definitions in a namespace

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#299]
Overloading of definitions with the same name seem not to always work properly:

```
import data.nat
namespace foo
open nat
check nat.zero
inductive nat : Type := zero, foosucc : nat → nat
check succ 0
check nat.zero
check 0 + nat.zero --error
end foo

namespace foo
check nat.succ nat.zero --error
end foo

-- the following checks work fine

section
open foo
check nat.succ nat.zero
open nat foo.nat
check succ zero
check foosucc zero
end
```

Also, the second error message might need some improvement:

```
type mismatch at application
  nat.succ nat.zero
term
  nat.zero
has type
  nat
but is expected to have type
  nat
```

(in the line of: give more details if the only difference between the "type" and "expected type" are hidden).
for example:

```
type mismatch at application
  nat.succ nat.zero
term
  nat.zero
has type
  foo.nat
but is expected to have type
  nat
```

(note: this is low priority to me, I just opened the issue since I noticed the behavior)

**Comment by leodemoura** [comment]
The error

```
check 0 + nat.zero --error
```

is the correct behavior.
We are in the namespace `foo`, and it contains `foo.nat.zero`. Thus any occurrence of `nat.zero` is just `foo.nat.zero` (overloading is disabled). This is the standard behavior in some programming languages (e.g., C++). We discussed it in the mailing list. Note that if we don't use this semantics, we would have to write

```
infixl `+` := int.add
```

instead of

```
infixl `+` := add
```

in the integer library. Otherwise, it would mean

```
infixl `+` := choice nat.add int.add
```

Moreover, since nat also defines `+` to be `nat.add`, we would have the overloaded `+` with a nested overloaded `add`. 

BTW, in your example, we can still refer to the `nat.zero` by writing `_root_.nat.zero`

**Comment by leodemoura** [comment]
I will improve the error message. Lean is supposed to automatically reveal hidden information when this kind of thing happens. I will investigate what it didn't work in this example.

**Comment by leodemoura** [comment]
The error message has been improved. See commit above.

**Comment by fpvandoorn** [comment]
Ah, yeah, I forgot about that discussion. Indeed, when opening a namespace, it is the right behavior to disable overloading.

Minor remark: If a user gets the error message, (s)he might still be confused why this is an error, and think that the overloading somehow fails (that is what I thought when I got the error, even though we already discussed the issue before). Maybe it would help if the error message contained something like "objects in the current namespace shadow objects with the same name outside the namespace" (display this when full names are needed to distinguish the given type and expected type).

**Comment by leodemoura** [comment]
The piece of code that generates the type error is not "aware" overloading exists. It is hard for the type checking module to be sure what is the root of the problem. It knows that two terms are not definitionaly equal when they are supposed to be.

**Comment by fpvandoorn** [comment]
Okay, I understand. I thought that maybe you could do something like "if the pretty printer shows full names then also display extra message" (showing full names happens - I think - precisely when some name is shadowed by another name)
