### ISSUE TITLE
class inference after abstraction

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#301]
The following fails:

```
import logic.decidable
theorem foo (P : Prop) : decidable P → decidable P := λ H, _
```

I think what happens here is that the class inference algorithm kicks in almost immediately, because there are no metavariables in the type anymore. However, then `H` is not yet elaborated. If we give an extra hint about the type of `H` it does work:

```
theorem foo (P : Prop) : decidable P → decidable P := λ (H : decidable _), _
```

I'm not sure whether we can support this behavior in general, because we want to do the class inference mechanism as early as possible. So it's probably expensive to first elaborate other metavariables to see whether they can be used as instances.

Leo, do you see a not to expensive way to allow this? If not, then I'm fine if you just close this issue as-is. I was just confused why the class inference mechanism didn't kick in for a slightly more involved example.

**Comment by leodemoura** [comment]
I think we can minimize this kind of "brittleness". 
At least for cases where it is "cheap" to infer the type of the local instance `H`.
By "cheap", I mean: the type of `H` can be inferred using only first-order unification.
This is the case in the example above.
Is this the case for your more involved example?

**Comment by fpvandoorn** [comment]
I'm afraid not. The more involved example uses induction:

```
definition trunc_succ (A : Type₁) (n : trunc_index) [H : is_trunc n A] : is_trunc (n.+1) A :=
trunc_index.rec_on n
  (λ A (H : is_contr A), !is_trunc_succ)
  (λ n IH A (H : is_trunc (n.+1) A), @is_trunc_succ _ _ (λ x y, IH _ !succ_is_trunc))
  A H
```

(it's in [trunc.lean](https://github.com/fpvandoorn/lean/blob/master/library/hott/trunc.lean#L82-87))
In both the base case and induction step, the `H` is needed for the class inference. The code above works, but leaving out the type of `H` in base case or induction step will make the class inference fail.

**Comment by leodemoura** [comment]
I don't see a reasonable solution for `trunc.lean`. The only solution I see is: wait to resolve an instance until the local context has been elaborated. This solution is not feasible, it would negatively affect many files. In general, we may have to keep "waiting" for completely irrelevant information to be available until we instantiate instances. 
As you pointed out, we want to be able to instantiate the instances as early as possible.

I will soon write a tutorial/manual about class-instance resolution. I will emphasize that only "explicit" local instances are considered.

**Comment by fpvandoorn** [comment]
That makes sense. We could still implement the partial solution when first-order unification is sufficient, but I don't know whether that gives us much.

**Comment by fpvandoorn** [comment]
Remark: If you remove the abstraction, and the remainder can be inferred just by "_", then the class inference mechanism will succeed. For example, the following does work:

```
theorem foo (P : Prop) : decidable P → decidable P := _
```

and if I mark `is_trunc_succ` as an instance I can replace the whole base case (`(λ A (H : is_contr A), !is_trunc_succ)`) by `_`. (however, `is_trunc_succ` and `succ_is_trunc` are converses of each other, so can't be both instances)

I understand why this happens, but it is still funny that giving less information helps the elaboration in this case.

**Comment by leodemoura** [comment]
I will close this issue. If we find a use for the first-order case, we can reopen this issue.
Otherwise, it is simpler to explain the way it is now.
