### ISSUE TITLE
max notation precedence

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#308]
In `trunc.lean` I define the following notation with maximal precedence
`postfix `.+1`:max := trunc_index.trunc_S`
However, `f n .+1` is parsed as `(f n) .+1` instead of `f (n .+1)`. 
Is this intended? Am I interpreting max precedence wrong?

**Comment by leodemoura** [comment]
function application has "infinity" precedence.

**Comment by avigad** [comment]
Floris, I can tell you what I know about the parser next time we meet. This
sort of thing also has to go into the documentation.

On Fri, Nov 7, 2014 at 12:13 AM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
The internal "max" precedence is not infinity anymore. 
The token "max" refers to this value. It is 1024.
I will allow expressions such as "max+1" when setting expressions (like we have for instance priorities).
Here is an example for Floris:
https://github.com/leanprover/lean/blob/b5e0ded163aab24b87fea964ba16d04161307f9f/tests/lean/notation7.lean

All the tests passed after this modification, but we may still have some glitches in the parser and/or pretty printer.

**Comment by fpvandoorn** [comment]
Looks good.

Two remarks:
- I think it would be good if `max` refers to something higher than the internal application precedence
- The pretty printer prints `is_trunc (n.+1) A` as `is_trunc n .+1 A` even if the precedence of `.+1` is very low
