### ISSUE TITLE
[emacs] autocompletion pop-up disappears when typing "."

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#311]

**Comment by soonhokong** [comment]
@fpvandoorn, can you give me a small example to reproduce?

**Comment by fpvandoorn** [comment]
Type

```
import standard
check tru
```

now press TAB (pop-up shows up and the `tru` becomes `true`), now type `.` (for example, you want `true.rec`), and the pop-up disappears.
Also, pressing TAB after that doesn't display the pop-up, but inserts a tab.

**Comment by fpvandoorn** [comment]
Works well, thanks!
