### ISSUE TITLE
autocompletion doesn't recognize names in opened namespace

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#313]
If you start a file with

```
import standard
open nat
```

then the definiton `nat.mul` is only available as `mul` and not as `nat.mul` in the autocompletion popup. Sometimes, however, you want to give the namespace explicitly because `mul` might be overloaded.

Note: `nat.mul.comm` and `mul.comm` are still both available (as desired)

**Comment by soonhokong** [comment]
1. I think this is an intended behavior. For this particular example, when you type `mul`, it always means `nat.mul`. 
2. However if you open both of `nat` and `int`, there are overloadings. Then, the autocompletion shows both of `nat.mul` and `int.mul`.

```
import standard
open nat
open int

check mul
         ^
```

@leodemoura, could you confirm that my explanation is correct and close the issue if you think this is actually a feature?

**Comment by fpvandoorn** [comment]
Okay, that makes sense and sounds good.

**Comment by leodemoura** [comment]
> @leodemoura, could you confirm that my explanation is correct and close the issue if you think this is actually a feature?

it is correct.

**Comment by soonhokong** [comment]
Thanks @leodemoura!
