### ISSUE TITLE
fold notation

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#314]
I tried to define notation for _n_-ary tuples for dependent pairs.

Is it possible to modify the following command
`notation `(` h `,` t:(foldl `,` (e r, prod.mk r e) h) `)` := t`
such that `(a,b,c,d)` is interpreted as `(a,(b,(c,d)))`?

I tried something like `notation `(` t:(foldr `,` (e r, sigma.dpair e r) h) `,` h `)` := t`, but then I get the error that `h` is an unknown identifier.

I was planning to put this notation in a separate namespace `sigma.ops` (together with postfixes `.1` and `.2` for the projections), but still it might be useful to make the notation different from the non-dependent tuples. I can make the brackets different, but I don't know how to make the commas a different symbol. Just replacing the two substrings ``,`` by something else doesn't work. 

Also: any suggestions for the notation of dependent pairs? e.g. `( a ; b )`  `[ a , b ]`  `[ a ; b ]`

**Comment by fpvandoorn** [comment]
Ah, I just realized the notation `.1` and `.2` are not so good, because they clash with the notation for namespaces. `x.1` can be interpreted as object `1` in namespace `x`, so we need a space between `x` and `.1`. This might not be so bad, but maybe some other notation is better. Suggestions?

**Comment by leodemoura** [comment]
> Is it possible to modify the following command
> notation `(` h `,` t:(foldl `,` (e r, prod.mk r e) h) `)` := t
> such that (a,b,c,d) is interpreted as (a,(b,(c,d)))?

I will add a variation of `foldr` and `foldl` where we do not provide the "initial element". 
Right now, we have to use a hack and add use something like `unit.star` as the initial element:

```
notation `(` t:(foldr `,` (e r, prod.mk e r) unit.star) `)` := t
```

Regarding `;`, we have two options:
1- set its left-binding-power to `0` like `,`. Any character with left-binding-power == 0 acts as a delimiter.

```
notation `(` t:(foldr `;`:0 (e r, prod.mk e r) unit.star) `)` := t
```

2- Change the right-binding-power used to parse the elements of the sequence. The default is 1 (super low). If we set it to 55 (just above relation such as <, =, ...) we can parse terms, and avoid setting the left-binding-power of `;`.

```
notation `(` t:(foldr 30 `;` (e r, prod.mk e r) unit.star) `)` := t
```

BTW, we use `;` as the `and-then` tactical combinator.

**Comment by leodemoura** [comment]
> x.1 can be interpreted as object 1 in namespace x

We can disallow that. It seems weird to have this kind of name. 
It looks like a bug. We can write

```
definition x.1 := 10
```

but Lean rejects

```
namespace x
definition 1 := 10
end x
```

**Comment by fpvandoorn** [comment]
Nice. Works well!

**Comment by javra** [comment]
As I have no proper reasons for or against one of your proposals for
dependent pairs, I'd say let's either mimic Coq and use ( a ; b ) or use
\langle a , b \rangle as usual in Set Theory and some other parts of math..

2014-11-09 17:33 GMT-05:00 Floris van Doorn notifications@github.com:

**Comment by leodemoura** [comment]
> use \langle a , b \rangle as usual in Set Theory and some other parts of math..

I like this.
BTW, we can also input them by typing `\<` and `\>`.

**Comment by avigad** [comment]
< and > already have precedences (binding powers). Do they make sense for
this notation?

On Mon, Nov 10, 2014 at 9:57 AM, Leonardo de Moura <notifications@github.com

**Comment by leodemoura** [comment]
Jakob meant the left-right angle characters: `⟨ ⟩`.

We can input them using `\langle` and `\rangle`, or `\<` and `\>`.

**Comment by avigad** [comment]
Oh, sounds good. It is a little confusing to have both (a, b) and <a, b>.
Using (a; b) looks more uniform with (a, b). But both are o.k. with me.

**Comment by fpvandoorn** [comment]
I'm slightly in favor of `(a; b)` (same as Coq, and a little easier to type), but I don't care too much either.

I do have a little trouble with both notations though. When opening the `tactic` namespace, `(a; b)` doesn't work, because `;` is interpreted as `tactic.and_then` (though as far as I can see the tactic framework works perfectly even without opening the `tactic` namespace). The notation `⟨a, b⟩` doesn't get recognized. Do I need to add precedences for the parentheses?

Both errors:

```
import tools.tactic
structure sigma {A : Type} (B : A → Type) := dpair :: (dpr1 : A) (dpr2 : B dpr1)
open sigma
notation `⟨` t:(foldr `,` (e r, dpair e r)) `⟩` := t
notation `(` t:(foldr `;`:0 (e r, dpair e r)) `)` := t
open tactic
variables {A B : Type} (a : A) (b : B)
check dpair a b
check ⟨ a , b ⟩
check ( a ; b )
```

**Comment by leodemoura** [comment]
> I do have a little trouble with both notations though. When opening the tactic namespace, (a; b) doesn't work, because ; is interpreted as tactic.and_then (though as far as I can see the tactic framework works perfectly even without opening the tactic namespace).

The `begin ... end` and `by ...` constructs open the tactic namespace for us (if it is not already open).
The downside is that we might still have problems if we try to use `(a; b)` inside of a tactic.

> The notation ⟨a, b⟩ doesn't get recognized. Do I need to add precedences for the parentheses?

Lean is using `1` as the default for left-binding-power (of tokens) and right-binding power for parsing arguments.  So, to get the behavior we want, we should use

```
notation `⟨` t:(foldr `,` (e r, dpair e r)) `⟩`:0 := t
```

or

```
notation `⟨` t:(foldr 2 `,` (e r, dpair e r)) `⟩` := t
```

That being said, it seems we should change the default for the right-binding power of arguments.
If we set the default for arguments to be `2`, then we can write both notation declarations as:

```
notation `⟨` t:(foldr `,` (e r, dpair e r)) `⟩` := t
notation `(` t:(foldr `;` (e r, dpair e r)) `)` := t
```

There is no need to provide the any binding power explicitly.

BTW, I will write the documentation for notation declarations today. We should make sure the default values are good and produce the expected behavior.

**Comment by fpvandoorn** [comment]
> The begin ... end and by ... constructs open the tactic namespace for us (if it is not already open).
> The downside is that we might still have problems if we try to use (a; b) inside of a tactic.

Ok, that sounds like more than enough reason for me not to use semicolons. I'll use `⟨a, b⟩`

> BTW, I will write the documentation for notation declarations today.

That would be nice!
