### ISSUE TITLE
[question] intros

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#326]
Is there an abbreviation for a sequence of multiple intros?
`intro u1, intro u2, intro q, intro r, intro s,`
Looking at the definitions in `tools.tactic`, it looks like something like `intros (u1, u2, q, r, s)` should work, but then I get the error that `intros` is not a function.

**Comment by leodemoura** [comment]
The directory `tests/lean/run` has some `intros` examples.
Could you post the example where you got the weird error message?

Thanks,
Leo

**Comment by fpvandoorn** [comment]
Oops, this was not a bug, but it was my fault. I forgot the comma after `intros (u1, u2, q, r, s)`.

Nice feature! Until I looked around in `tools.tactic` I thought I had to introduce variables 1 by 1 with `intro` (or use `intros` without specifying the names of the variables myself), but it's nice there is a shortcut :-)
