### ISSUE TITLE
generalize

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#327]
The tactic `generalize` currently doesn't remove the variable from the context. Is it possible to do so, and raise an error when that's not possible (when the variable is referenced in the context)? I think you never need to keep the variable in the context, right? 

Also, an abbreviation for

```
generalize x1, generalize x2, ... , generalize xn
```

would be nice.

**Comment by leodemoura** [comment]
`generalize` can be applied to arbitrary terms.
Example:

```
import data.nat
open nat

theorem tst (a b : nat) : a + b ≤ succ (a + b) :=
begin
  generalize (a+b),
  intro n,
  apply le_imp_le_succ,
  apply le_refl
end
```

What about a "delete hypothesis" tactic?

We can add an abbreviation to `generalize x1, ..., generalize xn`.

**Comment by avigad** [comment]
In Coq, as I recall, the tactic is called "clear".

On Fri, Nov 21, 2014 at 7:15 PM, Leonardo de Moura <notifications@github.com

**Comment by fpvandoorn** [comment]
I'm indeed confusing `generalize` with `revert` in Coq, which is the "inverse" of `intro`. A `clear` tactic would indeed be useful, and then `revert` can be simply defined as the composite of `generalize` and `clear` (I think).
