### ISSUE TITLE
unsolved metavariables

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#329]
I received the error "value has unsolved metavariables" after finishing a proof using tactics, I think incorrectly. 
This issue is probably in the category "behavior which seems strange, but which has a perfectly good explanation in the end", so feel free to delay investigating this issue.

The problem is [here](https://github.com/fpvandoorn/lean/blob/2e534ea3e4eca7ff66f80c9879446aa18f07298d/library/hott/types/sigma.lean#L195-200):

```
definition path_path_sigma_lemma' {p1 : a ≈ a'} {p2 : p1 ▹ b ≈ b'} {q2 : p1 ▹ b ≈ b'}
    (s : idp ▹ p2 ≈ q2) : path_sigma p1 p2 ≈ path_sigma p1 q2 :=
--path.rec_on s idp
begin
  apply (path.rec_on s), apply idp
end
```

The error I get is

```
 failed to add declaration 'path_path_sigma_lemma'' to environment, value has metavariables
  λ (A : Type) (B : A → Type) (a a' : A) (b : B a) (b' : B a') (p1 : a ≈ a') (p2 q2 : p1 ▹ b ≈ b')
  (s : @idp Type₁ (p1 ▹ b ≈ b') ▹ p2 ≈ q2),
    @path.rec_on (p1 ▹ b ≈ b') (@idp Type₁ (p1 ▹ b ≈ b') ▹ p2)
      (λ (a_1 : p1 ▹ (a ; b) .2 ≈ (a' ; b') .2) (n : ?M_1 ≈ a_1),
         @path_sigma A (λ (x : A), B x) (a ; b) (a' ; b') p1 p2 ≈ @path_sigma A (λ (a : A), B a) (a ; b) (a' ; b')
           p1
           a_1)
      q2
      s
      (@idp ((a ; b) ≈ (a' ; b')) (@path_sigma A (λ (x : A), B x) (a ; b) (a' ; b') p1 p2))
```

The strange thing is that the unsolved variable is the following variable of `path.rec_on`:

```
path.rec_on : Π {A : Type} {a : A} {C : Π (a_1 : A), a ≈ a_1 → Type} {a_1 : A} (n : a ≈ a_1), C a (idpath a) → C a_1 n
                                                     ^
```

I can hardly imagine that you can apply `path.rec_on` where that variable is not determined, since it should be the same as the earlier argument `{a : A}`. Is this a bug?

Note: the commented out proof does work.

**Comment by leodemoura** [comment]
I will investigate.
BTW, I noticed you are using tactics. There is a buffer called _lean-info_.
It is useful to split the window in 2 and keep _lean-info_ buffer visible.
Given a `begin ... end` block, if you put the cursor over the `,`, lean-mode will display the proof state for you.

**Comment by fpvandoorn** [comment]
Ah, that buffer is awesome! I guess I'll have that as my secondary buffer, instead of `*compilation*`, from now on.
So far I relied on the `unsolved goal` error messages when hovering over `end`.

The tactics are really nice. I usually use it when the unifier starts complaining that I have too many nested inductions.
