### ISSUE TITLE
protected definitions in nested namespaces

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#331]
Suppose we have a **protected** definition `foo1.foo2.bar`. Opening the namespaces `foo1` or `foo1.foo2` doesn't shorten the name of `foo1.foo2.bar`. 

Is it possible to change this behavior to allow to shorten `foo1.foo2.bar` to `foo2.bar` (by opening `foo1`), but not allowing it to shorten to `bar` (by opening `foo1.foo2`)? I think that if we specify only the innermost namespace (`foo2`) of a protected definition, this will never lead to overloads in practice.

For example, in the namespace `truncation` I define the inductive type `trunc_index`, but that means recursion on it is only available as `truncation.trunc_index.rec_on`, even if we opened the namespace `truncation`.

**Comment by leodemoura** [comment]
I see.
So, the `protected` modifier would only affect the immediate namespace.
This seems to be reasonable.
I don't see any problem with the new semantics for the `protected` modifier.

In the documentation, we would say something like:
The `protected` modifier affects the generation of aliases. By default, when we open a namespace `N` the system creates aliases for the declarations in `N`. When we use `protected`, the system will not create the alias `foo` for a declaration `N.foo`. The `protected` modifier only affects the immediate namespace where it was used. That is, if we declared foo in the namespace `M.N`, the system would still create the alias `N.foo` whenever we open `M`. 

We also have to consider the following "corner case"

```
namespace M
namespace N
   protected definition bar.bla := ...
end N
end M
open M -- creates alias N.bar.bla
open N -- does *not* create alias bar.bla
```

That is, the definition above is not equivalent to

```
namespace M
namespace N
namespace bar
  protected bla := ...
end bar 
end N
end M
```

This is consistent with the way we treat modifiers such as `[coercion]`, `[instance]`, etc.

What about the following scenario?

```
namespace foo
   protected definition bla.bar := ...
end foo
```

**Comment by fpvandoorn** [comment]
I think the simplest way to explain it is that the "innermost `.`" cannot be removed. So in your examples `M.N.bar.bla` can be reduced to both `N.bar.bla` and `bar.bla` by opening namespaces (in both cases) and `foo.bla.bar` can be reduced to `bla.bar`. I think that should be enough to never cause name clashes in practice. 
However, I really don't care about these "edge cases", so if there's any argument in favor of doing it in the way you suggested (like consistency with modifiers, or easier to code), that's also fine.

**Comment by leodemoura** [comment]
@fpvandoorn I implemented your suggestion.
It is easy to explain to users.
It was also easier to implement :-)
