### ISSUE TITLE
class inference fails

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#333]
The class inference problem in the following minimal example fails.

```
inductive is_equiv [class] (A B : Type) (f : A → B) : Type
definition inverse (A B : Type) (f : A → B) [H : is_equiv A B f] := Type
definition foo (A : Type) (B : A → Type) (h : A → A) (g : Π(a : A), B a → B a) 
               [H : Π(a : A), is_equiv _ _ (g a)] (x : A) : Type :=
inverse (B (h x)) (B (h x)) (g (h x))
```

Ways to make the error disappear:
- replacing _both_ underscores by their values `(B a)`
- replace `h x` by `x` everywhere
- replace `B _` by `A` everywhere

I assume the error is caused because the class inference mechanism kicks in before the implicit arguments of the type of `H` are solved, which makes it unavailable for class inference.

This is similar to issue #301. There are differences why I think this one should be solved (if possible):
- I'm still giving the most important part of the type of `H`, and in practice I should not be required to give the underscores explicitly (those arguments of `is_equiv` should really be implicit; I made them explicit only to make the example simpler)
- `H` is given as argument to the definition. I think that implicit arguments part of the type of a definition/theorem should be solved first, where-ever possible (changing `foo` to a theorem doesn't solve the issue, which I find strange, because I thought that the type of a theorem should be known before the proof is elaborated).

(Feel free to disallow me to post any more "class inference fails" issues, if those are low priority)

**Comment by leodemoura** [comment]
I think the feature we discussed at #301 should fix this issue.

> H is given as argument to the definition. I think that implicit arguments part of the type of a definition/theorem should be solved first,

This is only true for theorems. For definitions, we elaborate the type and value simultaneously.
We do that, because some users like to write definitions such as

```
 definition double x := x + x
```
