### ISSUE TITLE
typeclass structure making too many arguments implicit?

### ISSUE THREAD

**Issue by javra** [leanprover/lean#344]
When defining equivalence like this:

```
structure is_equiv [class] {A B : Type} (f : A → B) :=
  (inv : B → A)
  (retr : Sect inv f)
  (sect : Sect f inv)
  (adj : Πx, retr (f x) ≈ ap f (sect x))

check @is_equiv.inv
```

all the projections are no single explicit argument which makes them hard to use? Is there some way to change this?

**Comment by leodemoura** [comment]
This is the default behavior for "class structures". Note that we rely on that in the algebraic hierarchy. There we really want things such as `mul` to not take the structure as an argument.
Another justification is that, for classes, the structure instances should be synthesized using information from the context.

If we don't use the `[class]` modifier, then all projections will take the structure as an explicit argument.

Note that we can use the following trick for defining a "class structure" where the structure is not an implicit argument of the projections:
1- We define the structure without using `[class]`, and then
2- We use the command

```
class [persistent] is_equiv
```

That being said, ideas/suggestions on how to improve this structure command are welcome.

**Comment by javra** [comment]
Hm, in this case I would like to have the structure itself inferred by class inference but the parameter to the structure to be explicit, so I can write `inv f`. But maybe that's a rare use case and I should just leave it as an `inductive` definition. (Making `f` implicit gives the unification a hard time in a proof with multiple equivalences involved as well as terms like `inv \o inv` just look strange.)

**Comment by leodemoura** [comment]
What about 

```
structure is_equiv [class] {A B : Type} (f : A → B) :=
  (inv' : B → A)
  (retr : Sect inv' f)
  (sect : Sect f inv')
  (adj : Πx, retr (f x) ≈ ap f (sect x))
```

And then, we define

```
definition inv {A B : Type} (f : A -> B) [e : is_equiv f] := inv'
```

Then, at least, you don't have to define all projection "by hand".

**Comment by fpvandoorn** [comment]
> That being said, ideas/suggestions on how to improve this structure command are welcome.

Currently, an argument is made implicit, if it can be inferred from (the type of) a later argument, right? Or is it more complicated than that? 
I think if you change that to "an argument `f` is made implicit if it can inferred from a later argument `H` and `H` is not inferred by the type class mechanism (i.e. `H` is not within square brackets)".

This change will solve this problem, and I think it is in general the desired behavior.

**Comment by leodemoura** [comment]
> I think if you change that to "an argument f is made implicit if it can inferred from a later argument H and H is not inferred by the type class mechanism (i.e. H is not within square brackets)".

This is good!

We can simplify and say: `f` can be inferred from an _explicit_ later argument.

**Comment by leodemoura** [comment]
@fpvandoorn I just tried your suggestion, and there is a "corner case" as usual :-(

```
structure has_one [class] (A : Type) :=
(one : A)
```

The type of `one` would become `one (A : Type) [c : has_one A] : A`.
So, I switched to non-strict implicit inference. So, a parameter will be implicit in a projection if
1- It occurs in a later _explicit_ argument.
2- It occurs in the result type

For inductive datatypes, we use 'strict' implicit inference for introduction rule parameters.
So, the rule above may seem confusing. We can claim this is fine since `one` is not an introduction rule but a projection.

**Comment by fpvandoorn** [comment]
I actually think that even in that case `has_one.one` should have `A` as explicit argument. Sure, in this case you want `A` as implicit argument, but then you can use `!one`, or the notation `1` (where `A` is implicit). And sometimes you want `A` as explicit argument. For example, if you want to state `1 * 1 = 1` in a monoid, you still need the explicit argument at least once.

So in the current behavior, in the structure of `is_equiv`, do `retr`, `sect` and `adj` have `f` as implicit argument? I think there `f` should really be explicit. Sure, sometimes the elaborator will easily find `f`, but I think about half of the time we want `f` be explicit in those cases, so it's easier to have `f` explicit, and use `!adj` if `f` can be implicit.

**Comment by leodemoura** [comment]
I see.

> So in the current behavior, in the structure of is_equiv, do retr, sect and adj have f as implicit argument?

Yes, `f` is implicit. If switch back to strict inference, then it will be explicit again.

Making it strict will also make the behavior uniform with the inductive command.

**Comment by leodemoura** [comment]
I will switch to strict.

**Comment by fpvandoorn** [comment]
> I think if you change that to "an argument f is made implicit if it can inferred from a later argument H and H is not inferred by the type class mechanism (i.e. H is not within square brackets)".

---

> We can simplify and say: f can be inferred from an explicit later argument.

I just noticed that those two statements are not equivalent. In the following structure, consider the projection `category.id`.

```
structure category [class] (ob : Type) : Type :=
  (hom : ob → ob → Type)
  (compose : Π⦃a b c : ob⦄, hom b c → hom a b → hom a c)
  (id : Π {a : ob}, hom a a)
  (assoc : Π ⦃a b c d : ob⦄ (h : hom c d) (g : hom b c) (f : hom a b),
     compose h (compose g f) = compose (compose h g) f)
  (id_left : Π ⦃a b : ob⦄ (f : hom a b), compose id f = f)
  (id_right : Π ⦃a b : ob⦄ (f : hom a b), compose f id = f)
```

The argument `{a : ob}` is implicit, so the argument `(ob : Type)` cannot be inferred from an explicit argument, hence it will be explicit itself. In this case we want it to be implicit.

However, I'm not sure whether we want to change it, maybe in other situations it's the other way around, and we would like the `ob` to be explicit. So it's fine with me to leave it as is, in this particular case I can easily work around it.

**Comment by leodemoura** [comment]
> However, I'm not sure whether we want to change it, maybe in other situations it's the other way around, and we would like the ob to be explicit.

I agree. I think the right solution is to support `{}` modifier like we do for inductive datatypes.

I think the current semantics is reasonable, it is consistent with the approach used for inductive datatypes, and it is "friendly" to the elaborator.

The whnf trick I suggested in the other thread is not good. I think it will produce counter-intuitive behavior. Example: an argument becomes implicit after several reduction steps are applied to the range.
