### ISSUE TITLE
problem with 'INSERT' command (lean-server)

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#35]
I was testing the <kbd>lean-show-type</kbd> function, and found a problem with `INSERT` command.

First, open `library/standard/data/list/basic.lean` file and send a query about line 280:

```
VISIT /home/soonhok/work/lean/library/standard/data/list/basic.lean
INFO 280
/home/soonhok/work/lean/library/standard/data/list/basic.lean:17:0: warning: imported file uses 'sorry'
-- BEGININFO
-- TYPE|280|21
Type
-- ACK
-- TYPE|280|29
Type → Type
-- ACK
-- TYPE|280|34
Type
-- ACK
-- TYPE|280|42
Type
-- ACK
-- TYPE|280|47
Type
-- ACK
-- ENDINFO
```

Good, let's insert "-- comment" at line 280.

```
INSERT 280
-- comment
```

I expect we have the same information at line 281 (since the old line 280 is shifted to 281)

```
INFO 281
/home/soonhok/work/lean/library/standard/data/list/basic.lean:225:0: warning: imported file uses 'sorry'
-- BEGININFO
-- ENDINFO
```

There is nothing. To make sure, I send more queries:

```
INFO 280
-- BEGININFO
-- ENDINFO
INFO 279
-- BEGININFO
-- ENDINFO
INFO 282
-- BEGININFO
-- ENDINFO
INFO 283
-- BEGININFO
-- ENDINFO
```

Note that I added `-- BEGININFO` at the beginning of INFO messages.

**Comment by leodemoura** [comment]
The problem is the cache used in the server. The type information is collected during elaboration. The second time the buffer is processed the cache is used and no information is collected. I disabled the cache for now. We should find a better way to use the cache and preserve the type information.
