### ISSUE TITLE
apply generates too few subgoals

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#356]
When I'm in a proof using tactics, and I want to `apply` the following theorem:

```
definition path_sigma_dpair (p : a ≈ a') (q : p ▹ b ≈ b') : dpair a b ≈ dpair a' b'
```

I get a single subgoal `?p ▹ b ≈ b'`. I would much prefer to get two subgoals `p : a ≈ a'` and `p ▹ b ≈ b'`. 

I understand that you don't always want to create a subgoal for every explicit argument, because sometimes you can infer them from the context, for example the `k` can be inferred when using

```
theorem add_le_right {n m : ℕ} (H : n ≤ m) (k : ℕ) : n + k ≤ m + k
```

Maybe it can create a subgoal for every unsolved explicit argument?

**Comment by fpvandoorn** [comment]
I can of course just use `apply (path_sigma_dpair p)`, but that might be annoying if `p` is a big proof itself. 

However, I'm asking for the type of the second subgoal to depend on the "content" of the first subgoal, and I don't know whether we allow that (it would be strange if we solve the second subgoal first). If we don't, that's also fine, and I'll just give `p` explicitly.

**Comment by leodemoura** [comment]
The `apply` tactic will not generate subgoals for arguments that occur in later arguments.
It will also generate subgoals from left to right. This behavior seems to make sense in most cases.
For example, consider

```
exists_intro : ∀ {A : Type} {P : A → Prop} (a : A), P a → Exists P
```

We don't want to generate a subgoal for `a:A`. It would be very annoying to use `apply`.
We would have to keep rotating goals to solve `P a` first, and then trivially solving `a : A`.

That being said, we have a tactic called `rapply`. It is like apply but it adds goals for _all_ unassigned arguments. It adds the arguments from right to left. Thus, in the `exists_intro` example above the goal `P a` occurs first, and no "rotation" needs to be performed.

We can also add another version of `fapply` that it like apply but also adds all unassigned arguments as subgoals.

**Comment by fpvandoorn** [comment]
Ah, okay, that makes sense. I think the tactic I requested is `rapply` with the goals in reverse order. Can you give an example why it is useful that `rapply` has the goals in that order?

Another question: is there already a tactic similar to Coq's `simp`, i.e. to simplify the goal (or hypotheses) by beta-delta(-eta?)-iota reducing it?

**Comment by leodemoura** [comment]
> Ah, okay, that makes sense. I think the tactic I requested is rapply with the goals in reverse order. Can you give an example why it is useful that rapply has the goals in that order?

The `exists_intro` is an example. 
The motivation is that whenever we have dependent types:

```
a_1 : A_1, a_2 : A_2 [a_1], a_3 : A_3 [a_1, a_2], ...
```

by solving from left to right we may solve earlier goals too.
This is what happens in `exists_intro`.

> Another question: is there already a tactic similar to Coq's simp, i.e. to simplify the goal (or hypotheses) by beta-delta(-eta?)-iota reducing it?

We have `beta`, `unfold <f>`, and `whnf`. I can add more. These are easy to add, since the tactic does very little: it just invokes the evaluator, and no proof needs to be generated.
