### ISSUE TITLE
add fake dependency to LEAN_VERSION fake file

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#43]
The idea is to force the library to be recompiled whenever we update the executable/version

**Comment by soonhokong** [comment]
For the record, let me add some comments on it.

Now `*.d` and `*.olean` have a dependency on `bin/version` file. Then the questions is how to manage this `bin/version` file. There are some choices:
1. Manually update `bin/version` when we think people need to rebuild the library.
2. Let cmake maintain `bin/version` file. For example, whenever `LEAN_VERSION_MAJOR`, `LEAN_VERSION_MINOR`, or `LEAN_VERSION_PATCH` changes, cmake will update `bin/version` file. However, it's still our responsibility to bump up the version.
