### ISSUE TITLE
problem: $(LEAN_VERSION_FILE) on Makefile.common

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#49]
It does not work on Linux.
I had to remove it to be able to compile the Lean libraries from scratch.

**Comment by soonhokong** [comment]
It was because we have `LEAN=${CMAKE_BINARY_DIR}/shell/lean` in CMakeLists.txt file

https://github.com/leanprover/lean/blob/master/src/CMakeLists.txt#L318

I changed it to `LEAN=${CMAKE_SOURCE_DIR}/../bin/lean` and it solved the problem.

Do you want me to fix this and commit?

**Comment by leodemoura** [comment]
Yes, that would be great. I 'm working on the cache.
