### ISSUE TITLE
lean-mode: auto-complete doesn't work at the end of buffer

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#54]

**Comment by soonhokong** [comment]
It seems that this is a bug on emacs.

http://lists.gnu.org/archive/html/help-gnu-emacs/2013-02/msg00113.html

**Comment by leodemoura** [comment]
It seems this bug has been fixed. At least, it is working for me now.

**Comment by soonhokong** [comment]
Thanks for the report. I'll check other versions and platforms, then close it if it works everywhere.

**Comment by soonhokong** [comment]
@fpvandoorn, could you also check whether auto-completion is working with the latest version?

**Comment by fpvandoorn** [comment]
Yes, auto-completion works for me at the end of the buffer now
