### ISSUE TITLE
lean server: caching and implicit arguments

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#58]
open a file and enter the following:

  import logic
  theorem test (T : Type) (x : T) : x = x := refl _
  theorem test2 (A : Type) (a : A) : a = a := test A a

Then make the first argument to test implicit:

  theorem test {T : Type} (x : T) : x = x := refl _

Flycheck fails to report a error in test2 unless / until test2 is actually changed. With 

  #erase_cache test2

the behavior is corrected.

**Comment by avigad** [comment]
I see. In general, this can happen with any change that breaks elaboration but not type checking, for example, making arguments implicit, changing or removing a tactic, adding rewrite rules, etc.

I am also not sure how best to handle it, other than an option to build from scratch. 

lmake will find problems when it recompiles files. Maybe it would be helpful to have a version of "lmake all" accessible from emacs, so that users can check downstream consequences of their changes.

**Comment by leodemoura** [comment]
Yes, exactly. 
I think we can minimize the problem by 
1- "Ctrl-c-Ctrl-l" compiles current file without using the cache. We can use it to check the current file.
2- "lmake all" builds everything from scratch. We can use it to check the whole project. 
BTW, a build from scratch is already performed when we push our changes to github.

**Comment by leodemoura** [comment]
@soonhokong, I'm closing this issue. It is a duplicate (see https://github.com/leanprover/lean/issues/75)

`M-x lean-clear-cache` can be used as a temporary workaround.
