### ISSUE TITLE
flycheck does not seem to work if there is no makefile

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#60]
Create a .lean file at /tmp/.
We don't get any feedback from flycheck.
This is bad, novice users will use a single file and will not have a makefile.

**Comment by soonhokong** [comment]
@leodemoura, there was a bug not generating .olean file when there was no makefile. However, flycheck still works on my machine (both of OSX and Linux) even in /tmp directory without a makefile. Could you check the following two things?
- You have 'FlyC' next to 'Lean' in your [mode-line](http://www.emacswiki.org/emacs/ModeLine) bar.
- There is no flycheck error in `flycheck-error-list` (<kbd>C-c ! l</kbd>)

Could you provide me the result of `~/projects/lean/bin/lmake --flycheck /tmp/blah.lean`?

**Comment by soonhokong** [comment]
It turns out that there was no flycheck installed on the machine. `lean-mode` produces an error message:

```
File mode specification error: (file-error "Cannot open load file" "flycheck")
```

when a user opens a `.lean` file without having `flycheck` package and the custom variable `lean-flycheck-use` is `t` (which has a default value `t`).
