### ISSUE TITLE
lean-mode: syntax highlight for embedded lua code in lean file

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#74]

**Comment by leodemoura** [comment]
Relevant links

https://github.com/purcell/mmm-mode
https://github.com/vitoshka/polymode

**Comment by leodemoura** [comment]
This does not work. 
- Open an empty .lean file
- Type

```
(*
*)
```
- Now, inside of the `(* ... *)` block, type `local x = 10`. The Lua syntax highlighter is not active.
  Note that in the status-bar, we don't see `Lean[Lua]`.
- Close and open the file. Now, the Lua mode is active for the block `(* ... *)`.
  BUT, the flycheck is confused. It seems it is actually using flycheck for Lua?!?!?

Unless this is easy to fix, I suggest we remove this feature.
We can simply highlight the block `(* ... *)` like a comment. It is not nice, but at least is usable.
The current solution is unusable.

**Comment by soonhokong** [comment]
There is a related issue at mmm-mode, https://github.com/purcell/mmm-mode/issues/32. It says:

> So you're supposed to insert new regions using mmm-insert-region, which is by default bound to C-c % <char>, and the chars are defined in the :insert spec in the submode class definitions.

I just added this. Now if you open a new file `empty.lean` and press <kbd>C-c % l</kbd>, it will provide an empty lua section where syntax highlighting is enabled:

```
(* 

*)
```

> BUT, the flycheck is confused. It seems it is actually using flycheck for Lua?!?!?

Inside of the lua block, flycheck is disabled. You will see `FlyC-` at the mode-line where `-` sign indicates that it's disabled. It seems that the author of flycheck is not going to support mmm-mode in a recent future (https://github.com/flycheck/flycheck/issues/349)

> We can simply highlight the block (\* ... *) like a comment. It is not nice, but at least is usable. The current solution is unusable.

Do you think that this is still not usable and it's better to handle lua blocks as comments?

**Comment by leodemoura** [comment]
> Inside of the lua block, flycheck is disabled. You will see FlyC- at the mode-line where - sign
> indicates that it's disabled. 

Not for me.

> Do you think that this is still not usable and it's better to handle lua blocks as comments?

The current one is really bad. If you try to use it you will see how bad it is.
At least if we treat lua code blocks as a comment block, the TAB works in a reasonable way, we don't get spurious flycheck errors, the syntax highlight works in a predictable way.

**Comment by soonhokong** [comment]
@leodemoura, I disabled it and treated it like comments. Then it looked too monotone. Then I found some workarounds:
- Disable 'lua' check inside of lean (f94e28c)
- Use `mmm-parse-when-idle` to highlight lua regions (11ff7b5)

We still need to close a lua section to be syntax-highlighted. Other than that, I think it's OK to use. What do you think?
