### ISSUE TITLE
lean-mode: use two lean processes for flycheck (with and without cache)

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#75]

**Comment by leodemoura** [comment]
@soonhokong and I decided to fix this issue on the Lean side.
The idea is to track dependencies and store them on .clean files.

On the emacs side, we will just delete .clean files whenever we visit a buffer.

Related issue: the command `lean-clear-cache` should also delete the .clean file.

**Comment by soonhokong** [comment]
> Related issue: the command lean-clear-cache should also delete the .clean file.

This is the case. Calling `lean-clear-cache` function on emacs invokes `linja clear-cache` which delete all `.clean` files in the project. I am adding this item to `lean-mode-menu`.

**Comment by leodemoura** [comment]
Cool!
