### ISSUE TITLE
use 'proof - qed' for creating independent elaboration problems.

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#82]

**Comment by leodemoura** [comment]
It turns out this feature creates some problems.
If we process the proof-qed's on demand, then we must elaborate the context. Otherwise, we get really weird error messages.

```
  fun f, 
      have H : ....,
      proof
         ....   <<< when we elaborate this proof-qed, the type of f is not known 
      qed
      .... Rest ...
```

Since the type of `f` is not known when we process the `proof ... qed` block, we can solve the constraints associated with the `proof ... qed` block by assigning an arbitrary type to `f`. The error is only detected when we elaborate `Rest`.

This is an artificial example but it is based on a real one. 
The theorem `rec_measure_aux_spec` at 
https://github.com/leanprover/lean/blob/master/library/data/nat/div.lean
I added some proof-qed's to it, and got weird error messages because we try to use

```
    rec_decreasing : ∀g m x, m ≥ measure x → 
          rec_val x g = rec_val x (restrict default measure g m)
```

before it is fully elaborated.

Possible solutions:
1) We eagerly elaborate the context.
Pros: Improves performance, and it is easier for users to understand the order terms are elaborated.
Cons: Some patterns we use will not be supported. For example, the example above will not be supported. There is no way to find the type of f before we process "have H : ..., proof ... qed".
This may not be all bad, the example above is artificial. The following example will be supported

```
      have H1 : ..., from ....,
      have H2 : ...., 
      proof 
           .... <<< type of H1 has already been elaborated when we process H2 
      qed
```

2) We encode "proof T qed" as "by (determ (exact T))"
The main problem of this solution is that it relies on tactics. 
For example, term T is not really processed until we execute the tactic. We cannot even catch `unknown identifier` error until we execute the tactic. 
 We would also have to use '[fact]' to make sure that term T can view other terms in the context. The previous example would have to be encoded as:

```
      have H1 [fact] : ..., from ....,
      have H2 : ...., 
      proof 
           .... <<< H1 is visible here only if we mark it as a [fact] 
      qed
```

We can avoid the `[fact]` annotation by making the whole context visible for `proof-qed`.

3) Use a choice constraint. It is not really a `choice`, We use the choice constraint just to delay processing the `proof ... qed` block. It is very similar to the tactic solution, but avoids all the drawbacks associated with tactics.

**Comment by avigad** [comment]
Dear Leo,

I read this earlier and thought about it while driving home. Evaluating the
context eagerly sounds like the right thing to do. The pattern is supposed
to make it possible to outline a long proof, and then fill in subproofs,
without allowing crazy unification problems and backtracking that might
happen if we did everything at once.

Usually we build a context in a long proof with a sequence of lets, haves,
and obtains. As long as those objects (from the outside) are visible within
a block, it should work, I think. Evaluating the context first should do
that, shouldn't it?

Best wishes,

Jeremy
